import java.util.ArrayList;
import java.util.HashSet;


public class Main
{
  public static void main (String[] args)
  {

    String[] dictionary =
    {
    "the", "of", "and", "to", "in", "is", "you", "that", "it", "he", "was",
    "for", "on", "are", "with", "as", "his", "at", "by", "they", "one",
    "have", "this", "from", "or", "we", "when", "her", "all", "an",
    "my", "be", "which", "would", "their", "there", "who", "him",
    "what", "so", "about", "out", "but", "two", "can", "over", "after",
    "again", "any", "now", "some", "like", "than", "just", "me",
    "before", "into", "other", "most", "don't", "such", "no", "only",
    "down", "right", "because", "under", "well", "people", "up", "way",
    "every", "old", "long", "how", "new", "its", "them", "those",
    "going", "see", "more", "man", "could", "our", "first", "water",
    "make", "life", "going", "number", "year", "sound", "part", "house",
    "problem", "run", "keep", "land", "car", "night", "work", "take",
    "people", "get", "put", "day", "going", "come", "do", "say",
    "think", "call", "very", "new", "good", "big", "high", "young",
    "same", "different", "small", "large", "important", "complete",
    "full", "grow", "change", "open", "close", "write", "read", "tell",
    "ask", "wish", "happen", "move", "turn", "round", "clean", "form",
    "cut", "add", "spend", "happen", "turn", "class", "field", "study",
    "book", "answer", "school", "student", "teacher", "lesson", "point",
    "line", "face", "side", "plan", "figure", "space", "ground", "eat",
    "drink", "stay", "visit", "talk", "sing", "dance", "laugh", "cry",
    "sleep", "dress", "cold", "warm", "dry", "wet", "dark", "light",
    "heavy", "soft", "hard", "straight", "round", "square", "triangle",
    "circle", "winter", "spring", "summer", "fall", "morning",
    "afternoon", "evening", "night", "Monday", "Tuesday", "Wednesday",
    "Thursday", "Friday", "Saturday", "Sunday", "January", "February",
    "March", "April", "May", "June", "July", "August", "September",
    "October", "November", "December", "because", "but", "can", "come",
    "could", "day", "do", "don't", "down", "each", "else", "everyone",
    "everything", "family", "find", "first", "five", "for", "found",
    "from", "get", "give", "go", "going", "good", "got", "great", "had",
    "has", "have", "he", "her", "here", "him", "his", "how", "I", "if",
    "in", "into", "is", "it", "its", "just", "keep", "know", "large",
    "last", "like", "little", "long", "look", "made", "make", "man",
    "many", "me", "men", "might", "more", "most", "my", "never", "new",
    "next", "night", "no", "not", "now", "of", "off", "old", "on",
    "one", "only", "or", "other", "our", "out", "over", "own", "part",
    "people", "perhaps", "place", "play", "please", "put", "rather",
    "real", "right", "said", "same", "saw", "say", "see", "seem", "she",
    "should", "show", "since", "small", "so", "some", "something",
    "sometimes", "soon", "sound", "still", "such", "take", "talk",
    "tell", "than", "that", "the", "their", "them", "then", "there",
    "these", "they", "thing", "think", "this", "those", "though",
    "three", "through", "time", "to", "today", "together", "too", "try",
    "two", "under", "until", "up", "us", "use", "very", "want", "was",
    "way", "we", "well", "were", "what", "when", "where", "which",
    "while", "who", "why", "will", "with", "within", "without", "work",
    "would", "year", "you", "your", "after", "all", "almost", "always",
    "among", "around", "ask", "back", "because", "before", "below",
    "best", "better", "between", "both", "but", "buy", "call", "cannot",
    "catch", "children", "choice", "come", "could", "different",
    "during", "either", "else", "enough", "every", "except", "example",
    "family", "far", "few", "find", "first", "follow", "food", "for",
    "forget", "friend", "from", "full", "get", "give", "go", "good",
    "great", "guess", "hard", "has", "have", "head", "hear", "help",
    "here", "high", "home", "hope", "house", "how", "however",
    "important", "in", "inside", "instead", "into", "job", "just",
    "keep", "kind", "know", "last", "learn", "least", "left", "like",
    "little", "live", "long", "look", "love", "made", "make", "many",
    "may", "mean", "meet", "might", "more", "most", "move", "must",
    "near", "need", "never", "next", "nor", "not", "now", "number",
    "of", "off", "often", "old", "on", "once", "only", "open", "or",
    "other", "out", "outside", "over", "own", "part", "pass", "people",
    "perhaps", "person", "place", "play", "please", "point", "possible",
    "present", "put", "quick", "quite", "rather", "read", "ready",
    "real", "really", "reason", "receive", "remember", "rest", "right",
    "round", "same", "say", "school", "see", "seem", "send", "serious",
    "several", "should", "show", "side", "sign", "simple", "since",
    "small", "smart", "some", "something", "sometimes", "soon", "sorry",
    "sound", "special", "still", "study", "such", "sure", "take",
    "talk", "teach", "tell", "than", "thank", "that", "the", "their",
    "them", "then", "there", "these", "they", "thing", "think", "this",
    "those", "though", "thought", "three", "through", "time", "today",
    "together", "too", "toward", "try", "under", "until", "up", "upon",
    "use", "usual", "very", "want", "was", "watch", "water", "way",
    "we", "well", "went", "were", "what", "when", "where", "whether",
    "which", "while", "who", "whole", "whose", "why", "will", "with",
    "within", "without", "work", "would", "write", "year", "yes", "you",
    "your", "above", "account", "across", "act", "age", "ago", "agree",
    "air", "all", "allow", "almost", "alone", "along", "already",
    "also", "always", "among", "amount", "any", "anyone", "anything",
    "appear", "apple", "application", "apply", "appoint", "approach",
    "appropriate", "area", "argue", "arm", "around", "arrive",
    "article", "artist", "as", "ask", "assume", "at", "attack",
    "attend", "attention", "attorney", "audience", "author",
    "available", "avoid", "award", "aware", "away", "baby", "back",
    "bad", "bag", "balance", "ball", "band", "bank", "bar", "base",
    "basis", "be", "bear", "beat", "beautiful", "because", "become",
    "bed", "before", "begin", "behavior", "behind", "believe",
    "benefit", "best", "better", "between", "beyond", "big", "bill",
    "bit", "black", "blood", "blue", "board", "boat", "body", "book",
    "born", "both", "bother", "bottle", "bottom", "bought", "boy",
    "break", "bring", "brother", "brown", "build", "building",
    "business", "but", "buy", "by", "call", "came", "can", "cancer",
    "cannot", "capital", "captain", "car", "card", "care", "carry",
    "case", "catch", "cause", "cell", "center", "central", "century",
    "certain", "certainly", "chair", "challenge", "chance", "change",
    "character", "charge", "chart", "check", "child", "children",
    "choice", "choose", "church", "circle", "city", "claim", "class",
    "clean", "clear", "clearly", "client", "climate", "climb", "clock",
    "close", "cloth", "clothes", "cloud", "club", "coach", "coast",
    "coat", "code", "coffee", "cold", "collect", "college", "color",
    "come", "comfort", "command", "common", "community", "company",
    "compare", "complete", "completely", "complex", "computer",
    "condition", "conduct", "conference", "confess", "confidence",
    "confirm", "conflict", "confront", "confused", "connect",
    "consider", "consist", "constant", "construct", "contain",
    "content", "continue", "contract", "contrast", "contribute",
    "control", "conversation", "cook", "cool", "copy", "corner",
    "correct", "cost", "could", "count", "country", "couple", "course",
    "court", "cover", "cow", "create", "credit", "crime", "criminal",
    "crisis", "cross", "crowd", "cry", "culture", "cup", "curious",
    "current", "customer", "cut", "cycle", "dad", "damage", "dance",
    "danger", "daughter", "day", "dead", "deal", "death", "debate",
    "decide", "decision", "declare", "decline", "deep", "defense",
    "degree", "delay", "deliver", "demand", "demonstrate", "depend",
    "describe", "design", "desire", "desk", "despite", "destroy",
    "detail", "determine", "develop", "different", "difficult",
    "dinner", "direct", "direction", "director", "discover", "discuss",
    "disease", "dismiss", "display", "distance", "distribute",
    "district", "divide", "doctor", "document", "dog", "dollar", "door",
    "double", "doubt", "down", "dozen", "draft", "drag", "draw",
    "dream", "dress", "drink", "drive", "drop", "dry", "due", "during",
    "duty", "each", "ear", "early", "earn", "earth", "ease", "east",
    "easy", "eat", "edge", "effect", "effort", "eight", "either",
    "elderly", "elect", "electric", "element", "else", "elsewhere",
    "employee", "employ", "empty", "enable", "end", "energy", "engine",
    "engineer", "enjoy", "enough", "enter", "entire", "environment",
    "equal", "equipment", "error", "escape", "especially", "essential",
    "establish", "estate", "estimate", "etc", "even", "evening",
    "event", "eventually", "ever", "every", "everybody", "everyone",
    "everything", "evidence", "evil", "exact", "exactly", "examine",
    "example", "exceed", "excel", "excellent", "except", "exchange",
    "excite", "excited", "excitement", "excuse", "exercise", "exist",
    "expect", "expense", "experience", "expert", "explain", "explode",
    "explore", "express", "extend", "extent", "extra", "extreme", "eye",
    "face", "fact", "factor", "fail", "failure", "fair", "faith",
    "fall", "false", "family", "famous", "fan", "far", "farm",
    "fashion", "fast", "fat", "father", "favor", "favorite", "fear",
    "feature", "federal", "fee", "feel", "female", "few", "field",
    "fight", "figure", "fill", "film", "final", "finally", "financial",
    "find", "fine", "finger", "finish", "fire", "firm", "first", "fish",
    "fit", "five", "fix", "flag", "flat", "floor", "flow", "flower",
    "fly", "focus", "fold", "follow", "food", "foot", "for", "force",
    "foreign", "forest", "forget", "form", "formal", "former",
    "forward", "found", "four", "fourth", "frame", "free", "frequency",
    "fresh", "friend", "friendly", "from", "front", "fruit", "full",
    "fun", "function", "fund", "funny", "future", "gain", "game",
    "garage", "garden", "gas", "gate", "gather", "general", "generate",
    "gentle", "get", "gift", "girl", "give", "glad", "glass", "go",
    "goal", "god", "gold", "golf", "good", "government", "grab",
    "grade", "gradually", "graduate", "grain", "grand", "grandfather",
    "grandmother", "grant", "grass", "great", "green", "ground",
    "group", "grow", "growth", "guarantee", "guard", "guess", "guest",
    "guide", "guilty", "gun", "guy", "habit", "hair", "half", "hall",
    "hand", "handle", "happen", "happy", "hard", "hardly", "hat",
    "hate", "have", "he", "head", "health", "hear", "heart", "heat",
    "heavy", "height", "hello", "help", "her", "here", "herself",
    "hidden", "high", "highway", "hill", "him", "himself", "his",
    "history", "hit", "hold", "hole", "holiday", "home", "honest",
    "honey", "honor", "hook", "hope", "horse", "hospital", "hot",
    "hotel", "hour", "house", "how", "however", "huge", "human",
    "humor", "hundred", "hungry", "hunter", "husband", "hurt", "ice",
    "idea", "identify", "if", "ignore", "ill", "image", "imagine",
    "immediate", "impact", "important", "improve", "include", "income",
    "increase", "indeed", "indicate", "individual", "industry",
    "inform", "information", "initial", "initiative", "injury",
    "inside", "instance", "instead", "institute", "instruction",
    "insurance", "intend", "intense", "intention", "interest",
    "international", "internet", "interview", "introduce", "invest",
    "investigation", "invite", "involve", "iron", "issue", "it", "its",
    "itself", "jacket", "job", "join", "joint", "journal", "journey",
    "joy", "judge", "jump", "just", "keep", "key", "kick", "kid",
    "kill", "kind", "king", "kitchen", "knee", "knife", "knock", "know",
    "knowledge", "label", "labor", "lack", "lady", "lake", "land",
    "language", "large", "last", "late", "later", "laugh", "law",
    "lawyer", "lay", "lead", "leader", "league", "learn", "least",
    "leather", "leave", "lecture", "left", "leg", "legal", "lend",
    "length", "less", "lesson", "let", "letter", "level", "lie", "life",
    "light", "like", "likely", "limit", "line", "link", "list",
    "listen", "little", "live", "load", "local", "locate", "location",
    "lock", "long", "look", "loose", "lose", "loss", "lot", "loud",
    "love", "low", "lower", "luck", "lunch", "machine", "mad",
    "magazine", "mail", "main", "maintain", "major", "make", "male",
    "man", "manage", "manager", "manner", "many", "map", "march",
    "mark", "market", "marriage", "marry", "mass", "master", "match",
    "material", "matter", "may", "maybe", "mayor", "me", "meal", "mean",
    "meaning", "measure", "meat", "mechanic", "mechanism", "media",
    "medical", "medicine", "meet", "meeting", "member", "memory",
    "mention", "menu", "mere", "message", "metal", "method", "middle",
    "might", "mile", "military", "milk", "million", "mind", "mine",
    "minister", "minor", "minute", "miss", "mission", "mistake", "mix",
    "model", "modern", "moment", "money", "month", "mood", "moon",
    "more", "morning", "most", "mother", "motion", "motor", "mountain",
    "mouse", "mouth", "move", "movie", "Mr", "Mrs", "much", "multiply",
    "murder", "music", "must", "my", "myself", "mystery", "name",
    "nation", "national", "natural", "nature", "near", "nearly",
    "necessary", "neck", "need", "negative", "neighbor", "neither",
    "nerve", "net", "network", "never", "new", "news", "newspaper",
    "next", "nice", "night", "nine", "no", "nobody", "noise", "none",
    "nor", "normal", "north", "nose", "not", "note", "nothing",
    "notice", "now", "nowhere", "nuclear", "number", "nurse", "object",
    "observe", "obtain", "obvious", "occasion", "occur", "ocean", "of",
    "off", "offer", "office", "officer", "official", "often", "oh",
    "oil", "old", "on", "once", "one", "only", "onto", "open",
    "operate", "opinion", "opportunity", "opposite", "orange", "order",
    "ordinary", "organization", "original", "other", "otherwise",
    "ought", "ounce", "out", "outside", "over", "owe", "own", "owner",
    "pace", "pack", "package", "page", "pain", "paint", "pair",
    "palace", "pale", "pan", "paper", "park", "part", "particular",
    "particularly", "partner", "party", "pass", "passage", "past",
    "path", "patient", "pattern", "pay", "peace", "people", "per",
    "percent", "perfect", "perform", "perform", "perhaps", "period",
    "permit", "person", "personal", "pet", "phone", "physical", "piano",
    "pick", "picture", "piece", "place", "plan", "plant", "plastic",
    "plate", "play", "player", "please", "pleasure", "plenty", "pocket",
    "poem", "point", "police", "policy", "political", "politician",
    "pool", "poor", "pop", "popular", "population", "position",
    "positive", "possible", "possibly", "post", "pot", "pound", "pour",
    "practice", "prepare", "present", "president", "press", "pressure",
    "pretty", "price", "pride", "priest", "print", "prior", "private",
    "prize", "probably", "problem", "procedure", "process", "produce",
    "product", "profession", "professional", "professor", "profit",
    "program", "progress", "project", "promise", "promote", "proper",
    "property", "protect", "proud", "prove", "provide", "public",
    "publish", "pull", "punish", "purchase", "purpose", "push", "put",
    "quality", "quarter", "queen", "question", "quick", "quiet", "quit",
    "quite", "race", "radio", "rail", "rain", "raise", "range", "rate",
    "rather", "reach", "read", "ready", "real", "really", "reason",
    "receive", "recent", "recently", "recognize", "recommend", "record",
    "red", "reduce", "refer", "reflect", "reform", "refuse", "regard",
    "region", "register", "regular", "regulate", "relation",
    "relationship", "relative", "relax", "release", "religion",
    "religious", "remain", "remark", "remember", "remind", "remote",
    "remove", "rent", "repair", "repeat", "replace", "reply", "report",
    "represent", "republic", "reputation", "request", "require",
    "rescue", "research", "resemble", "reserve", "resign", "resist",
    "resort", "resource", "respect", "respond", "responsible", "rest",
    "restaurant", "result", "retire", "return", "reveal", "revenge",
    "reverse", "review", "reward", "rhythm", "rice", "rich", "rid",
    "ride", "right", "ring", "rise", "risk", "river", "road", "rock",
    "role", "roll", "room", "root", "rope", "rough", "round", "route",
    "row", "royal", "rule", "run", "rural", "rush", "sad", "safe",
    "safety", "sail", "sale", "salt", "same", "sample", "sand",
    "satisfy", "sauce", "save", "say", "scale", "scene", "schedule",
    "scheme", "school", "science", "score", "scream", "screen",
    "script", "sea", "search", "season", "seat", "second", "secret",
    "section", "secure", "see", "seed", "seek", "seem", "seize",
    "select", "self", "sell", "send", "senior", "sense", "sensitive",
    "sentence", "separate", "series", "serious", "serve", "service",
    "session", "set", "settle", "several", "severe", "sex", "shake",
    "shall", "shape", "share", "sharp", "she", "sheep", "sheet",
    "shelf", "shell", "shelter", "shift", "shine", "ship", "shirt",
    "shock", "shoe", "shoot", "shop", "short", "shot", "should",
    "shoulder", "shout", "show", "shower", "sick", "side", "sight",
    "sign", "signal", "silence", "silent", "silly", "silver", "similar",
    "simple", "since", "sing", "single", "sink", "sir", "sister", "sit",
    "site", "situation", "six", "size", "skill", "skin", "skirt", "sky",
    "sleep", "slice", "slide", "slight", "slip", "slow", "small",
    "smart", "smell", "smile", "smoke", "smooth", "snake", "snow", "so",
    "social", "society", "sock", "soft", "soil", "soldier", "solid",
    "solution", "solve", "some", "somebody", "someone", "something",
    "sometimes", "somewhere", "son", "song", "soon", "sorry", "sort",
    "soul", "sound", "soup", "source", "south", "space", "speak",
    "special", "specific", "speech", "speed", "spell", "spend",
    "spirit", "split", "spoil", "sport", "spot", "spread", "spring",
    "square", "stable", "staff", "stage", "stair", "stake", "stand",
    "standard", "star", "start", "state", "statement", "station",
    "stay", "steal", "steam", "steel", "step", "stick", "still", "stir",
    "stock", "stomach", "stone", "stop", "store", "storm", "story",
    "straight", "strange", "stranger", "strategy", "stream", "street",
    "strength", "stress", "stretch", "strike", "string", "strong",
    "structure", "student", "study", "stuff", "style", "subject",
    "submit", "substance", "succeed", "success", "such", "sudden",
    "suffer", "sugar", "suggest", "suit", "summer", "sun", "super",
    "supply", "support", "sure", "surface", "surprise", "surround",
    "survey", "suspect", "sustain", "swear", "sweet", "swim", "swing",
    "switch", "symbol", "system", "table", "tail", "take", "talk",
    "tall", "tank", "tape", "target", "task", "taste", "tax", "tea",
    "teach", "teacher", "team", "tear", "technology", "teenager",
    "telephone", "television", "tell", "temperature", "temporary",
    "ten", "tend", "tennis", "term", "terrible", "test", "than",
    "thank", "that", "the", "their", "them", "themselves", "then",
    "there", "therefore", "these", "they", "thick", "thin", "thing",
    "think", "third", "thirsty", "thirty", "this", "those", "though",
    "thought", "thousand", "threat", "three", "through", "throw",
    "throat", "throne", "truck", "true", "truly", "trust", "truth",
    "try", "tube", "turn", "twelve", "twenty", "twice", "twin", "two",
    "type", "typical", "ugly", "uncle", "under", "understand", "unit",
    "united", "universal", "university", "unless", "until", "up",
    "upon", "upper", "use", "useful", "usual", "usually", "valley",
    "valuable", "value", "variable", "variety", "various", "vary",
    "vast", "vegetable", "vehicle", "version", "very", "victim",
    "victory", "video", "view", "village", "violent", "virgin",
    "virtual", "visit", "visitor", "visual", "vital", "voice", "volume",
    "vote", "wage", "wait", "walk", "wall", "wander", "want", "war",
    "warm", "warn", "wash", "waste", "watch", "water", "wave", "way",
    "we", "weak", "wear", "weather", "weave", "web", "week", "weight",
    "weird", "welcome", "well", "west", "wet", "what", "whatever",
    "wheel", "when", "whenever", "where", "whereas", "wherever",
    "whether", "which", "while", "whisper", "white", "who", "whole",
    "whom", "whose", "why", "wide", "wife", "wild", "will", "win",
    "wind", "window", "wine", "wing", "winner", "winter", "wipe",
    "wire", "wisdom", "wise", "wish", "with", "within", "without",
    "witness", "woman", "wonder", "wonderful", "wood", "wool", "word",
    "work", "worker", "world", "worry", "worth", "would", "wound",
    "wrap", "write", "writer", "wrong", "yard", "yeah", "year",
    "yellow", "yes", "yesterday", "yet", "yield", "you", "young",
    "your", "yourself", "youth", "abandon", "ability", "absence",
    "absolute", "absorb", "abstract", "abundance", "accelerate",
    "accent", "access", "accident", "accomplish", "accurate", "achieve",
    "acknowledge", "acquire", "action", "adapt", "addition", "adequate",
    "admire", "admit", "advance", "adventure", "advice", "advocate",
    "affect", "afford", "agency", "agenda", "agent", "agriculture",
    "aid", "aim", "aircraft", "alarm", "align", "allocate",
    "alternative", "ambition", "amplify", "analyze", "ancient", "angle",
    "animal", "announce", "annual", "anticipate", "anxiety", "apparent",
    "approach", "appropriate", "approve", "argument", "arrange",
    "arrival", "article", "aspect", "assemble", "assert", "assess",
    "assign", "assist", "associate", "assume", "athlete", "atmosphere",
    "attach", "attain", "attempt", "attitude", "attract", "attribute",
    "audience", "authentic", "average", "awareness", "awesome",
    "balance", "barrier", "basic", "behavior", "belief", "belong",
    "benefit", "beverage", "biology", "boundary", "brave", "breathe",
    "brief", "brilliant", "broadcast", "builder", "bulletin", "burden",
    "calculate", "campaign", "capacity", "capture", "care", "carry",
    "case", "catch", "celebrate", "center", "century", "ceremony",
    "chamber", "chance", "change", "character", "charge", "chart",
    "check", "child", "choice", "choose", "church", "circle", "citizen",
    "city", "claim", "class", "clean", "clear", "climb", "close",
    "clothes", "cloud", "club", "coast", "coffee", "cold", "collect",
    "college", "combine", "comfort", "command", "comment", "commit",
    "common", "communicate", "community", "company", "compare",
    "compete", "complain", "complete", "complex", "compute",
    "concentrate", "concept", "concern", "concert", "condition",
    "conflict", "connect", "consider", "consist", "constant",
    "construct", "contact", "contain", "continue", "control",
    "contribute", "convention", "convince", "cook", "coordinate",
    "corporation", "correct", "council", "counsel", "count", "country",
    "couple", "courage", "course", "court", "cover", "create", "credit",
    "crew", "critic", "cross", "crowd", "crucial", "culture", "current",
    "curve", "custom", "damage", "dance", "danger", "dark", "data",
    "date", "daughter", "day", "dead", "deal", "debate", "debt",
    "decide", "declare", "deep", "defend", "define", "degree",
    "deliver", "demand", "department", "depend", "describe", "desire",
    "destroy", "detail", "determine", "develop", "device", "difference",
    "different", "difficult", "dilemma", "dimension", "dinner",
    "direct", "direction", "director", "discover", "discuss", "disease",
    "dismiss", "display", "distance", "distinguish", "distribute",
    "diverse", "divide", "document", "dollar", "domestic", "dominant",
    "double", "doubt", "dream", "drive", "drop", "earn", "earth",
    "easily", "east", "easy", "economic", "educate", "effective",
    "effort", "either", "elect", "electric", "element", "else",
    "embarrass", "emerge", "emergency", "emphasize", "employee",
    "employer", "employment", "encounter", "encourage", "end", "energy",
    "enforce", "engage", "engine", "engineer", "enhance", "enjoy",
    "enormous", "ensure", "enter", "entertain", "entire", "entity",
    "environment", "equal", "equivalent", "escape", "especially",
    "establish", "estimate", "evaluate", "even", "event", "eventually",
    "evidence", "exact", "examine", "example", "exceed", "excellent",
    "except", "exchange", "excuse", "execute", "exercise", "exist",
    "expand", "expect", "experience", "experiment", "expert", "explain",
    "explore", "express", "extend", "extension", "external",
    "extraordinary", "extreme", "face", "facility", "factor", "fail",
    "fair", "faith", "fall", "familiar", "family", "famous",
    "fantastic", "far", "farm", "fashion", "fast", "father", "favor",
    "favorite", "fear", "feature", "federal", "fee", "feel", "female",
    "festival", "few", "field", "fight", "figure", "file", "fill",
    "film", "final", "finance", "find", "fine", "finger", "finish",
    "fire", "firm", "first", "fit", "five", "fix", "flag", "flavor",
    "flight", "float", "floor", "flow", "flower", "focus", "fold",
    "follow", "food", "foot", "force", "foreign", "forest", "forever",
    "forget", "form", "formal", "fortune", "forward", "found", "four",
    "frame", "free", "freedom", "fresh", "friend", "front", "fruit",
    "fuel", "fun", "function", "fund", "funny", "future", "gain",
    "game", "gap", "garage", "garden", "gas", "gather", "general",
    "generate", "generation", "gentle", "genuine", "gesture", "get",
    "gift", "girl", "give", "glass", "goal", "god", "gold", "good",
    "govern", "government", "grace", "grade", "grand", "grant", "grass",
    "great", "green", "ground", "group", "grow", "growth", "guarantee",
    "guard", "guess", "guest", "guide", "guilt", "gun", "guy", "habit",
    "hair", "half", "hall", "hand", "handle", "hang", "happen", "happy",
    "hard", "harm", "hat", "hate", "have", "head", "heal", "health",
    "hear", "heart", "heat", "heavy", "help", "here", "hero", "hey",
    "hide", "high", "highlight", "highway", "hill", "hire",
    "historical", "history", "hit", "hold", "hole", "holiday", "home",
    "honest", "hope", "horizon", "horse", "hospital", "host", "hot",
    "hotel", "hour", "house", "how", "huge", "human", "humor",
    "hundred", "hungry", "hunt", "hurry", "hurt", "husband", "idea",
    "identify", "ignore", "ill", "illegal", "illness", "imagine",
    "impact", "implement", "importance", "important", "impose",
    "impress", "improve", "incentive", "incident", "include", "income",
    "increase", "independence", "influence", "inform", "information",
    "ingredient", "initial", "injury", "innovation", "input", "inside",
    "install", "instance", "instead", "institute", "instruct",
    "insurance", "integrate", "intention", "interaction", "interest",
    "internal", "international", "interview", "introduce", "invest",
    "investigate", "investigation", "invite", "involve", "iron",
    "island", "issue", "jacket", "job", "join", "joint", "journey",
    "judge", "judgment", "jump", "jury", "just", "justice", "keep",
    "key", "kick", "kid", "kill", "kind", "king", "kiss", "kitchen",
    "knee", "knife", "knock", "know", "knowledge", "lab", "labor",
    "lack", "lake", "land", "landscape", "language", "large", "last",
    "late", "later", "laugh", "launch", "law", "lawyer", "lay", "lead",
    "leader", "leadership", "leading", "league", "learn", "least",
    "leather", "leave", "lecture", "left", "leg", "legal", "legend",
    "leisure", "lesson", "letter", "level", "library", "lie", "life",
    "lift", "light", "like", "limit", "line", "link", "list", "listen",
    "literature", "little", "live", "load", "loan", "local", "location",
    "lock", "long", "look", "lose", "loss", "love", "low", "machine",
    "magazine", "mail", "main", "major", "majority", "make", "man",
    "manage", "management", "manager", "manner", "manufacturer", "many",
    "map", "march", "mark", "market", "marketing", "marriage", "master",
    "match", "material", "matter", "may", "maybe", "meal", "mean",
    "measure", "measurement", "meat", "media", "medicine", "medium",
    "meet", "meeting", "member", "membership", "memory", "mention",
    "message", "metal", "method", "middle", "might", "mile", "military",
    "milk", "mind", "mine", "minimum", "minute", "mirror", "miss",
    "mission", "mistake", "mix", "model", "modern", "moment", "money",
    "monitor", "month", "mood", "morning", "most", "mother", "motion",
    "motor", "mountain", "mouse", "mouth", "move", "movement", "movie",
    "much", "music", "muscle", "museum", "music", "mutual", "myth",
    "name", "narrow", "nation", "national", "natural", "nature", "near",
    "necessary", "neck", "need", "negative", "negotiate", "negotiation",
    "neighbor", "neighborhood", "neither", "nervous", "network",
    "never", "new", "news", "newspaper", "next", "nice", "night", "no",
    "nobody", "noise", "nomination", "none", "nor", "normal", "north",
    "nose", "not", "note", "nothing", "notice", "novel", "now",
    "nuclear", "number", "numerous", "obvious", "occasion",
    "occupation", "occur", "ocean", "odd", "off", "offer", "office",
    "officer", "official", "often", "oil", "ok", "old", "on", "once",
    "one", "only", "onto", "open", "operation", "opinion",
    "opportunity", "oppose", "opposite", "option", "or", "order",
    "ordinary", "organization", "organize", "origin", "other", "ought",
    "our", "out", "outcome", "outside", "oven", "over", "overall",
    "own", "owner", "pace", "pack", "package", "page", "pain", "paint",
    "pair", "pale", "pan", "panel", "paper", "parent", "park", "part",
    "participant", "participate", "particular", "particularly",
    "partly", "partner", "party", "pass", "passage", "passenger",
    "passion", "past", "path", "patient", "pattern", "pause", "pay",
    "peace", "peak", "pen", "penalty", "people", "per", "perceive",
    "percentage", "perception", "perfect", "perform", "performance",
    "perhaps", "period", "permanent", "permission", "permit", "person",
    "personal", "perspective", "persuade", "pet", "phase", "philosophy",
    "phone", "photo", "photograph", "phrase", "physical", "piano",
    "pick", "picture", "pie", "piece", "pile", "pilot", "pin", "pipe",
    "pitch", "place", "plan", "plane", "planet", "planning", "plant",
    "plastic", "plate", "platform", "play", "player", "please",
    "pleasure", "plenty", "plot", "plus", "pm", "pocket", "poem",
    "poet", "poetry", "point", "police", "policy", "political",
    "politics", "pool", "poor", "pop", "popular", "population", "port",
    "pose", "position", "positive", "possess", "possession",
    "possibility", "possible", "post", "pot", "potato", "potential",
    "pound", "poverty", "power", "powerful", "practice", "praise",
    "pray", "preach", "precious", "prefer", "preference", "pregnant",
    "preparation", "prepare", "presence", "present", "presentation",
    "preserve", "president", "press", "pressure", "pretend", "pretty",
    "prevent", "previous", "previously", "price", "pride", "priest",
    "primarily", "primary", "prime", "principal", "principle", "print",
    "prior", "priority", "prison", "private", "probably", "problem",
    "procedure", "proceed", "process", "produce", "producer", "product",
    "production", "profession", "professional", "professor", "profile",
    "profit", "program", "progress", "project", "prominent", "promise",
    "promote", "promotion", "prompt", "proof", "proper", "property",
    "proportion", "proposal", "propose", "prospect", "protect",
    "protection", "protein", "protest", "proud", "prove", "provide",
    "provider", "province", "provision", "psychological", "psychology",
    "public", "publication", "publicity", "publish", "pull",
    "punishment", "purchase", "pure", "purpose", "pursue", "pursuit",
    "push", "put", "qualify", "quality", "quantity", "quarter",
    "question", "quick", "quiet", "quietly", "quit", "quite", "quote",
    "race", "racial", "radical", "radio", "rail", "rain", "raise",
    "range", "rank", "rapid", "rare", "rate", "rather", "ratio", "raw",
    "reach", "react", "reaction", "read", "reader", "reading", "ready",
    "real", "reality", "realize", "really", "reason", "reasonable",
    "recall", "receive", "recent", "recently", "recipe", "recognition",
    "recognize", "recommend", "record", "recording", "recover",
    "recovery", "recruit", "red", "reduce", "reduction", "refer",
    "reference", "reflect", "reflection", "reform", "refuse", "regard",
    "regarding", "regardless", "regional", "register", "regret",
    "regular", "regulation", "reject", "relate", "relation",
    "relationship", "relative", "relatively", "relax", "release",
    "relevant", "relief", "religion", "religious", "rely", "remain",
    "remaining", "remark", "remember", "remind", "remote", "remove",
    "repeat", "replace", "reply", "report", "reporter", "represent",
    "representation", "representative", "republican", "reputation",
    "request", "require", "requirement", "research", "researcher",
    "resemble", "reservation", "resident", "resist", "resistance",
    "resolve", "resort", "resource", "respect", "respond", "response",
    "responsibility", "responsible", "rest", "restaurant", "restore",
    "restriction", "result", "retain", "retire", "retirement", "return",
    "reveal", "revenue", "review", "revolution", "rhythm", "rice",
    "rich", "rid", "ride", "rifle", "right", "ring", "rise", "risk",
    "river", "road", "rock", "role", "roll", "romantic", "roof", "room",
    "root", "rope", "rose", "rough", "round", "route", "routine", "row",
    "rub", "rule", "run", "running", "rural", "rush", "russian",
    "sacred", "safe", "safety", "sake", "salad", "salary", "sale",
    "sales", "salt", "same", "sample", "sanction", "sand", "satellite",
    "satisfaction", "satisfy", "sauce", "save", "saving", "say",
    "scale", "scandal", "scan", "scare", "scatter", "scenario", "scene",
    "schedule", "scheme", "scholar", "school", "science", "scientific",
    "scientist", "scope", "score", "scream", "screen", "script", "sea",
    "search", "season", "seat", "second", "secret", "secretary",
    "section", "sector", "secure", "security", "see", "seed", "seek",
    "seem", "segment", "seize", "select", "selection", "self", "sell",
    "senate", "senator", "send", "senior", "sense", "sensitive",
    "sentence", "separate", "sequence", "series", "serious",
    "seriously", "serve", "service", "session", "set", "setting",
    "settle", "settlement", "seven", "several", "severe", "sex",
    "sexual", "shade", "shadow", "shake", "shall", "shape", "share",
    "sharp", "she", "sheet", "shelf", "shell", "shelter", "shift",
    "shine", "ship", "shirt", "shock", "shoe", "shoot", "shop",
    "shopping", "shore", "short", "shortly", "shot", "should",
    "shoulder", "shout", "show", "shower", "shut", "sick", "side",
    "sight", "sign", "signal", "significance", "significant",
    "significantly", "silence", "silly", "silver", "similar",
    "similarly", "simple", "simply", "sin", "since", "sing", "singer",
    "single", "sink", "sir", "sister", "sit", "site", "situation",
    "size", "skill", "skin", "sky", "sleep", "slice", "slide", "slight",
    "slightly", "slip", "slow", "slowly", "small", "smart", "smell",
    "smile", "smoke", "smooth", "snap", "snow", "so", "so-called",
    "soccer", "social", "society", "soft", "software", "soil", "solar",
    "soldier", "solid", "solution", "solve", "some", "somebody",
    "somehow", "someone", "something", "sometimes", "somewhat",
    "somewhere", "son", "song", "soon", "sophisticated", "sorry",
    "sort", "soul", "sound", "soup", "source", "south", "southern",
    "soviet", "space", "spanish", "speak", "speaker", "special",
    "specialist", "species", "specific", "specifically", "speech",
    "speed", "spend", "spending", "spin", "spirit", "spiritual",
    "split", "spokesman", "sport", "spot", "spread", "spring", "square",
    "squeeze", "stability", "stable", "staff", "stage", "stair",
    "stake", "stand", "standard", "standing", "star", "stare", "start",
    "state", "statement", "station", "statistics", "status", "stay",
    "steady", "steal", "steel", "step", "stick", "still", "stir",
    "stock", "stomach", "stone", "stop", "storage", "store", "storm",
    "story", "straight", "strange", "stranger", "strategic", "strategy",
    "stream", "street", "strength", "stress", "stretch", "strike",
    "string", "strip", "stroke", "strong", "strongly", "structure",
    "struggle", "student", "studio", "study", "stuff", "stupid",
    "style", "subject", "submit", "subsequent", "substance",
    "substantial", "succeed", "success", "successful", "successfully",
    "such", "sudden", "suddenly", "sue", "suffer", "sufficient",
    "sugar", "suggest", "suggestion", "suicide", "suit", "summer",
    "summit", "sun", "super", "supply", "support", "supporter",
    "suppose", "supposed", "supreme", "sure", "surely", "surface",
    "surgery", "surprise", "surprised", "surprising", "surprisingly",
    "surround", "survey", "survival", "survive", "survivor", "suspect",
    "suspicion", "suspicious", "swim", "swing", "switch", "symbol",
    "symptom", "system", "table", "tablespoon", "tactic", "tail",
    "take", "tale", "talent", "talk", "tall", "tank", "tap", "tape",
    "target", "task", "taste", "tax", "taxpayer", "tea", "teach",
    "teacher", "teaching", "team", "tear", "technical", "technique",
    "technology", "teen", "teenager", "telephone", "telescope",
    "television", "tell", "temperature", "temporary", "ten", "tend",
    "tendency", "tennis", "tension", "tent", "term", "terms",
    "terrible", "territory", "terror", "terrorism", "terrorist", "test",
    "testify", "testimony", "testing", "text", "than", "thank",
    "thanks", "that", "the", "theater", "their", "them", "theme",
    "themselves", "then", "theory", "therapy", "there", "therefore",
    "these", "they", "thick", "thin", "thing", "think", "thinking",
    "third", "thirty", "this", "those", "though", "thought", "thousand",
    "threat", "threaten", "three", "throat", "through", "throughout",
    "throw", "thus", "ticket", "tie", "tight", "time", "tiny", "tip",
    "tire", "tired", "tissue", "title", "to", "tobacco", "today", "toe",
    "together", "tomorrow", "tone", "tongue", "tonight", "too", "tool",
    "tooth", "top", "topic", "toss", "total", "totally", "touch",
    "tough", "tour", "tourist", "tournament", "toward", "towards",
    "tower", "town", "toy", "trace", "track", "trade", "tradition",
    "traditional", "traffic", "tragedy", "trail", "train", "training",
    "transfer", "transform", "transformation", "transition",
    "translate", "translation", "transmission", "transport",
    "transportation", "trap", "trash", "travel", "treat", "treatment",
    "treaty", "tree", "tremendous", "trend"};
    
    ArrayList<String> dictionary2 = new ArrayList<>();
    HashSet<String> seen = new HashSet<>();
    for (String word : dictionary) {
      if (!seen.contains(word)) {
        dictionary2.add(word);
        seen.add(word);
      }
    }
    int g = 0;
    for (int i = 0; i < dictionary2.size(); i++)
      {
    System.out.print ("\"" + dictionary2.get(i) + "\"");
    g++;
    if (g < 4)
      {
        System.out.print(", ");
      }else{
        g = 0;
        System.out.println(", ");
      }
      }
  }
}