import java.util.ArrayList;

//This program will remove the duplicates and tell us
//which words had duplicates, how many times they appeared,
//and in the position number they appear.
public class DuplicateRemover3
{
  public static void main(String[] args)
  {
    String[] dictionary =
    {
    "the", "of", "and", "to", "in", "is", "you", "that", "it", "he", "was",
  "for", "on", "are", "with", "as", "his", "at", "by", "they", "one",
  "have", "this", "from", "or", "we", "when", "her", "all", "an",
  "my", "be", "which", "would", "their", "there", "who", "him",
  "what", "so", "about", "out", "but", "two", "can", "over", "after",
  "again", "any", "now", "some", "like", "than", "just", "me",
  "before", "into", "other", "most", "don't", "such", "no", "only",
  "down", "right", "because", "under", "well", "people", "up", "way",
  "every", "old", "long", "how", "new", "its", "them", "those",
  "going", "see", "more", "man", "could", "our", "first", "water",
  "make", "life", "going", "number", "year", "sound", "part", "house",
  "problem", "run", "keep", "land", "car", "night", "work", "take",
  "people", "get", "put", "day", "going", "come", "do", "say",
  "think", "call", "very", "new", "good", "big", "high", "young",
  "same", "different", "small", "large", "important", "complete",
  "full", "grow", "change", "open", "close", "write", "read", "tell",
  "ask", "wish", "happen", "move", "turn", "round", "clean", "form",
  "cut", "add", "spend", "happen", "turn", "class", "field", "study",
  "book", "answer", "school", "student", "teacher", "lesson", "point",
  "line", "face", "side", "plan", "figure", "space", "ground", "eat",
  "drink", "stay", "visit", "talk", "sing", "dance", "laugh", "cry",
  "sleep", "dress", "cold", "warm", "dry", "wet", "dark", "light",
  "heavy", "soft", "hard", "straight", "round", "square", "triangle",
  "circle", "winter", "spring", "summer", "fall", "morning",
  "afternoon", "evening", "night", "Monday", "Tuesday", "Wednesday",
  "Thursday", "Friday", "Saturday", "Sunday", "January", "February",
  "March", "April", "May", "June", "July", "August", "September",
  "October", "November", "December", "because", "but", "can", "come",
  "could", "day", "do", "don't", "down", "each", "else", "everyone",
  "everything", "family", "find", "first", "five", "for", "found",
  "from", "get", "give", "go", "going", "good", "got", "great", "had",
  "has", "have", "he", "her", "here", "him", "his", "how", "I", "if",
  "in", "into", "is", "it", "its", "just", "keep", "know", "large",
  "last", "like", "little", "long", "look", "made", "make", "man",
  "many", "me", "men", "might", "more", "most", "my", "never", "new",
  "next", "night", "no", "not", "now", "of", "off", "old", "on",
  "one", "only", "or", "other", "our", "out", "over", "own", "part",
  "people", "perhaps", "place", "play", "please", "put", "rather",
  "real", "right", "said", "same", "saw", "say", "see", "seem", "she",
  "should", "show", "since", "small", "so", "some", "something",
  "sometimes", "soon", "sound", "still", "such", "take", "talk",
  "tell", "than", "that", "the", "their", "them", "then", "there",
  "these", "they", "thing", "think", "this", "those", "though",
  "three", "through", "time", "to", "today", "together", "too", "try",
  "two", "under", "until", "up", "us", "use", "very", "want", "was",
  "way", "we", "well", "were", "what", "when", "where", "which",
  "while", "who", "why", "will", "with", "within", "without", "work",
  "would", "year", "you", "your", "after", "all", "almost", "always",
  "among", "around", "ask", "back", "because", "before", "below",
  "best", "better", "between", "both", "but", "buy", "call", "cannot",
  "catch", "children", "choice", "come", "could", "different",
  "during", "either", "else", "enough", "every", "except", "example",
  "family", "far", "few", "find", "first", "follow", "food", "for",
  "forget", "friend", "from", "full", "get", "give", "go", "good",
  "great", "guess", "hard", "has", "have", "head", "hear", "help",
  "here", "high", "home", "hope", "house", "how", "however",
  "important", "in", "inside", "instead", "into", "job", "just",
  "keep", "kind", "know", "last", "learn", "least", "left", "like",
  "little", "live", "long", "look", "love", "made", "make", "many",
  "may", "mean", "meet", "might", "more", "most", "move", "must",
  "near", "need", "never", "next", "nor", "not", "now", "number",
  "of", "off", "often", "old", "on", "once", "only", "open", "or",
  "other", "out", "outside", "over", "own", "part", "pass", "people",
  "perhaps", "person", "place", "play", "please", "point", "possible",
  "present", "put", "quick", "quite", "rather", "read", "ready",
  "real", "really", "reason", "receive", "remember", "rest", "right",
  "round", "same", "say", "school", "see", "seem", "send", "serious",
  "several", "should", "show", "side", "sign", "simple", "since",
  "small", "smart", "some", "something", "sometimes", "soon", "sorry",
  "sound", "special", "still", "study", "such", "sure", "take",
  "talk", "teach", "tell", "than", "thank", "that", "the", "their",
  "them", "then", "there", "these", "they", "thing", "think", "this",
  "those", "though", "thought", "three", "through", "time", "today",
  "together", "too", "toward", "try", "under", "until", "up", "upon",
  "use", "usual", "very", "want", "was", "watch", "water", "way",
  "we", "well", "went", "were", "what", "when", "where", "whether",
  "which", "while", "who", "whole", "whose", "why", "will", "with",
  "within", "without", "work", "would", "write", "year", "yes", "you",
  "your", "above", "account", "across", "act", "age", "ago", "agree",
  "air", "all", "allow", "almost", "alone", "along", "already",
  "also", "always", "among", "amount", "any", "anyone", "anything",
  "appear", "apple", "application", "apply", "appoint", "approach",
  "appropriate", "area", "argue", "arm", "around", "arrive",
  "article", "artist", "as", "ask", "assume", "at", "attack",
  "attend", "attention", "attorney", "audience", "author",
  "available", "avoid", "award", "aware", "away", "baby", "back",
  "bad", "bag", "balance", "ball", "band", "bank", "bar", "base",
  "basis", "be", "bear", "beat", "beautiful", "because", "become",
  "bed", "before", "begin", "behavior", "behind", "believe",
  "benefit", "best", "better", "between", "beyond", "big", "bill",
  "bit", "black", "blood", "blue", "board", "boat", "body", "book",
  "born", "both", "bother", "bottle", "bottom", "bought", "boy",
  "break", "bring", "brother", "brown", "build", "building",
  "business", "but", "buy", "by", "call", "came", "can", "cancer",
  "cannot", "capital", "captain", "car", "card", "care", "carry",
  "case", "catch", "cause", "cell", "center", "central", "century",
  "certain", "certainly", "chair", "challenge", "chance", "change",
  "character", "charge", "chart", "check", "child", "children",
  "choice", "choose", "church", "circle", "city", "claim", "class",
  "clean", "clear", "clearly", "client", "climate", "climb", "clock",
  "close", "cloth", "clothes", "cloud", "club", "coach", "coast",
  "coat", "code", "coffee", "cold", "collect", "college", "color",
  "come", "comfort", "command", "common", "community", "company",
  "compare", "complete", "completely", "complex", "computer",
  "condition", "conduct", "conference", "confess", "confidence",
  "confirm", "conflict", "confront", "confused", "connect",
  "consider", "consist", "constant", "construct", "contain",
  "content", "continue", "contract", "contrast", "contribute",
  "control", "conversation", "cook", "cool", "copy", "corner",
  "correct", "cost", "could", "count", "country", "couple", "course",
  "court", "cover", "cow", "create", "credit", "crime", "criminal",
  "crisis", "cross", "crowd", "cry", "culture", "cup", "curious",
  "current", "customer", "cut", "cycle", "dad", "damage", "dance",
  "danger", "daughter", "day", "dead", "deal", "death", "debate",
  "decide", "decision", "declare", "decline", "deep", "defense",
  "degree", "delay", "deliver", "demand", "demonstrate", "depend",
  "describe", "design", "desire", "desk", "despite", "destroy",
  "detail", "determine", "develop", "different", "difficult",
  "dinner", "direct", "direction", "director", "discover", "discuss",
  "disease", "dismiss", "display", "distance", "distribute",
  "district", "divide", "doctor", "document", "dog", "dollar", "door",
  "double", "doubt", "down", "dozen", "draft", "drag", "draw",
  "dream", "dress", "drink", "drive", "drop", "dry", "due", "during",
  "duty", "each", "ear", "early", "earn", "earth", "ease", "east",
  "easy", "eat", "edge", "effect", "effort", "eight", "either",
  "elderly", "elect", "electric", "element", "else", "elsewhere",
  "employee", "employ", "empty", "enable", "end", "energy", "engine",
  "engineer", "enjoy", "enough", "enter", "entire", "environment",
  "equal", "equipment", "error", "escape", "especially", "essential",
  "establish", "estate", "estimate", "etc", "even", "evening",
  "event", "eventually", "ever", "every", "everybody", "everyone",
  "everything", "evidence", "evil", "exact", "exactly", "examine",
  "example", "exceed", "excel", "excellent", "except", "exchange",
  "excite", "excited", "excitement", "excuse", "exercise", "exist",
  "expect", "expense", "experience", "expert", "explain", "explode",
  "explore", "express", "extend", "extent", "extra", "extreme", "eye",
  "face", "fact", "factor", "fail", "failure", "fair", "faith",
  "fall", "false", "family", "famous", "fan", "far", "farm",
  "fashion", "fast", "fat", "father", "favor", "favorite", "fear",
  "feature", "federal", "fee", "feel", "female", "few", "field",
  "fight", "figure", "fill", "film", "final", "finally", "financial",
  "find", "fine", "finger", "finish", "fire", "firm", "first", "fish",
  "fit", "five", "fix", "flag", "flat", "floor", "flow", "flower",
  "fly", "focus", "fold", "follow", "food", "foot", "for", "force",
  "foreign", "forest", "forget", "form", "formal", "former",
  "forward", "found", "four", "fourth", "frame", "free", "frequency",
  "fresh", "friend", "friendly", "from", "front", "fruit", "full",
  "fun", "function", "fund", "funny", "future", "gain", "game",
  "garage", "garden", "gas", "gate", "gather", "general", "generate",
  "gentle", "get", "gift", "girl", "give", "glad", "glass", "go",
  "goal", "god", "gold", "golf", "good", "government", "grab",
  "grade", "gradually", "graduate", "grain", "grand", "grandfather",
  "grandmother", "grant", "grass", "great", "green", "ground",
  "group", "grow", "growth", "guarantee", "guard", "guess", "guest",
  "guide", "guilty", "gun", "guy", "habit", "hair", "half", "hall",
  "hand", "handle", "happen", "happy", "hard", "hardly", "hat",
  "hate", "have", "he", "head", "health", "hear", "heart", "heat",
  "heavy", "height", "hello", "help", "her", "here", "herself",
  "hidden", "high", "highway", "hill", "him", "himself", "his",
  "history", "hit", "hold", "hole", "holiday", "home", "honest",
  "honey", "honor", "hook", "hope", "horse", "hospital", "hot",
  "hotel", "hour", "house", "how", "however", "huge", "human",
  "humor", "hundred", "hungry", "hunter", "husband", "hurt", "ice",
  "idea", "identify", "if", "ignore", "ill", "image", "imagine",
  "immediate", "impact", "important", "improve", "include", "income",
  "increase", "indeed", "indicate", "individual", "industry",
  "inform", "information", "initial", "initiative", "injury",
  "inside", "instance", "instead", "institute", "instruction",
  "insurance", "intend", "intense", "intention", "interest",
  "international", "internet", "interview", "introduce", "invest",
  "investigation", "invite", "involve", "iron", "issue", "it", "its",
  "itself", "jacket", "job", "join", "joint", "journal", "journey",
  "joy", "judge", "jump", "just", "keep", "key", "kick", "kid",
  "kill", "kind", "king", "kitchen", "knee", "knife", "knock", "know",
  "knowledge", "label", "labor", "lack", "lady", "lake", "land",
  "language", "large", "last", "late", "later", "laugh", "law",
  "lawyer", "lay", "lead", "leader", "league", "learn", "least",
  "leather", "leave", "lecture", "left", "leg", "legal", "lend",
  "length", "less", "lesson", "let", "letter", "level", "lie", "life",
  "light", "like", "likely", "limit", "line", "link", "list",
  "listen", "little", "live", "load", "local", "locate", "location",
  "lock", "long", "look", "loose", "lose", "loss", "lot", "loud",
  "love", "low", "lower", "luck", "lunch", "machine", "mad",
  "magazine", "mail", "main", "maintain", "major", "make", "male",
  "man", "manage", "manager", "manner", "many", "map", "march",
  "mark", "market", "marriage", "marry", "mass", "master", "match",
  "material", "matter", "may", "maybe", "mayor", "me", "meal", "mean",
  "meaning", "measure", "meat", "mechanic", "mechanism", "media",
  "medical", "medicine", "meet", "meeting", "member", "memory",
  "mention", "menu", "mere", "message", "metal", "method", "middle",
  "might", "mile", "military", "milk", "million", "mind", "mine",
  "minister", "minor", "minute", "miss", "mission", "mistake", "mix",
  "model", "modern", "moment", "money", "month", "mood", "moon",
  "more", "morning", "most", "mother", "motion", "motor", "mountain",
  "mouse", "mouth", "move", "movie", "Mr", "Mrs", "much", "multiply",
  "murder", "music", "must", "my", "myself", "mystery", "name",
  "nation", "national", "natural", "nature", "near", "nearly",
  "necessary", "neck", "need", "negative", "neighbor", "neither",
  "nerve", "net", "network", "never", "new", "news", "newspaper",
  "next", "nice", "night", "nine", "no", "nobody", "noise", "none",
  "nor", "normal", "north", "nose", "not", "note", "nothing",
  "notice", "now", "nowhere", "nuclear", "number", "nurse", "object",
  "observe", "obtain", "obvious", "occasion", "occur", "ocean", "of",
  "off", "offer", "office", "officer", "official", "often", "oh",
  "oil", "old", "on", "once", "one", "only", "onto", "open",
  "operate", "opinion", "opportunity", "opposite", "orange", "order",
  "ordinary", "organization", "original", "other", "otherwise",
  "ought", "ounce", "out", "outside", "over", "owe", "own", "owner",
  "pace", "pack", "package", "page", "pain", "paint", "pair",
  "palace", "pale", "pan", "paper", "park", "part", "particular",
  "particularly", "partner", "party", "pass", "passage", "past",
  "path", "patient", "pattern", "pay", "peace", "people", "per",
  "percent", "perfect", "perform", "perform", "perhaps", "period",
  "permit", "person", "personal", "pet", "phone", "physical", "piano",
  "pick", "picture", "piece", "place", "plan", "plant", "plastic",
  "plate", "play", "player", "please", "pleasure", "plenty", "pocket",
  "poem", "point", "police", "policy", "political", "politician",
  "pool", "poor", "pop", "popular", "population", "position",
  "positive", "possible", "possibly", "post", "pot", "pound", "pour",
  "practice", "prepare", "present", "president", "press", "pressure",
  "pretty", "price", "pride", "priest", "print", "prior", "private",
  "prize", "probably", "problem", "procedure", "process", "produce",
  "product", "profession", "professional", "professor", "profit",
  "program", "progress", "project", "promise", "promote", "proper",
  "property", "protect", "proud", "prove", "provide", "public",
  "publish", "pull", "punish", "purchase", "purpose", "push", "put",
  "quality", "quarter", "queen", "question", "quick", "quiet", "quit",
  "quite", "race", "radio", "rail", "rain", "raise", "range", "rate",
  "rather", "reach", "read", "ready", "real", "really", "reason",
  "receive", "recent", "recently", "recognize", "recommend", "record",
  "red", "reduce", "refer", "reflect", "reform", "refuse", "regard",
  "region", "register", "regular", "regulate", "relation",
  "relationship", "relative", "relax", "release", "religion",
  "religious", "remain", "remark", "remember", "remind", "remote",
  "remove", "rent", "repair", "repeat", "replace", "reply", "report",
  "represent", "republic", "reputation", "request", "require",
  "rescue", "research", "resemble", "reserve", "resign", "resist",
  "resort", "resource", "respect", "respond", "responsible", "rest",
  "restaurant", "result", "retire", "return", "reveal", "revenge",
  "reverse", "review", "reward", "rhythm", "rice", "rich", "rid",
  "ride", "right", "ring", "rise", "risk", "river", "road", "rock",
  "role", "roll", "room", "root", "rope", "rough", "round", "route",
  "row", "royal", "rule", "run", "rural", "rush", "sad", "safe",
  "safety", "sail", "sale", "salt", "same", "sample", "sand",
  "satisfy", "sauce", "save", "say", "scale", "scene", "schedule",
  "scheme", "school", "science", "score", "scream", "screen",
  "script", "sea", "search", "season", "seat", "second", "secret",
  "section", "secure", "see", "seed", "seek", "seem", "seize",
  "select", "self", "sell", "send", "senior", "sense", "sensitive",
  "sentence", "separate", "series", "serious", "serve", "service",
  "session", "set", "settle", "several", "severe", "sex", "shake",
  "shall", "shape", "share", "sharp", "she", "sheep", "sheet",
  "shelf", "shell", "shelter", "shift", "shine", "ship", "shirt",
  "shock", "shoe", "shoot", "shop", "short", "shot", "should",
  "shoulder", "shout", "show", "shower", "sick", "side", "sight",
  "sign", "signal", "silence", "silent", "silly", "silver", "similar",
  "simple", "since", "sing", "single", "sink", "sir", "sister", "sit",
  "site", "situation", "six", "size", "skill", "skin", "skirt", "sky",
  "sleep", "slice", "slide", "slight", "slip", "slow", "small",
  "smart", "smell", "smile", "smoke", "smooth", "snake", "snow", "so",
  "social", "society", "sock", "soft", "soil", "soldier", "solid",
  "solution", "solve", "some", "somebody", "someone", "something",
  "sometimes", "somewhere", "son", "song", "soon", "sorry", "sort",
  "soul", "sound", "soup", "source", "south", "space", "speak",
  "special", "specific", "speech", "speed", "spell", "spend",
  "spirit", "split", "spoil", "sport", "spot", "spread", "spring",
  "square", "stable", "staff", "stage", "stair", "stake", "stand",
  "standard", "star", "start", "state", "statement", "station",
  "stay", "steal", "steam", "steel", "step", "stick", "still", "stir",
  "stock", "stomach", "stone", "stop", "store", "storm", "story",
  "straight", "strange", "stranger", "strategy", "stream", "street",
  "strength", "stress", "stretch", "strike", "string", "strong",
  "structure", "student", "study", "stuff", "style", "subject",
  "submit", "substance", "succeed", "success", "such", "sudden",
  "suffer", "sugar", "suggest", "suit", "summer", "sun", "super",
  "supply", "support", "sure", "surface", "surprise", "surround",
  "survey", "suspect", "sustain", "swear", "sweet", "swim", "swing",
  "switch", "symbol", "system", "table", "tail", "take", "talk",
  "tall", "tank", "tape", "target", "task", "taste", "tax", "tea",
  "teach", "teacher", "team", "tear", "technology", "teenager",
  "telephone", "television", "tell", "temperature", "temporary",
  "ten", "tend", "tennis", "term", "terrible", "test", "than",
  "thank", "that", "the", "their", "them", "themselves", "then",
  "there", "therefore", "these", "they", "thick", "thin", "thing",
  "think", "third", "thirsty", "thirty", "this", "those", "though",
  "thought", "thousand", "threat", "three", "through", "throw",
  "throat", "throne", "truck", "true", "truly", "trust", "truth",
  "try", "tube", "turn", "twelve", "twenty", "twice", "twin", "two",
  "type", "typical", "ugly", "uncle", "under", "understand", "unit",
  "united", "universal", "university", "unless", "until", "up",
  "upon", "upper", "use", "useful", "usual", "usually", "valley",
  "valuable", "value", "variable", "variety", "various", "vary",
  "vast", "vegetable", "vehicle", "version", "very", "victim",
  "victory", "video", "view", "village", "violent", "virgin",
  "virtual", "visit", "visitor", "visual", "vital", "voice", "volume",
  "vote", "wage", "wait", "walk", "wall", "wander", "want", "war",
  "warm", "warn", "wash", "waste", "watch", "water", "wave", "way",
  "we", "weak", "wear", "weather", "weave", "web", "week", "weight",
  "weird", "welcome", "well", "west", "wet", "what", "whatever",
  "wheel", "when", "whenever", "where", "whereas", "wherever",
  "whether", "which", "while", "whisper", "white", "who", "whole",
  "whom", "whose", "why", "wide", "wife", "wild", "will", "win",
  "wind", "window", "wine", "wing", "winner", "winter", "wipe",
  "wire", "wisdom", "wise", "wish", "with", "within", "without",
  "witness", "woman", "wonder", "wonderful", "wood", "wool", "word",
  "work", "worker", "world", "worry", "worth", "would", "wound",
  "wrap", "write", "writer", "wrong", "yard", "yeah", "year",
  "yellow", "yes", "yesterday", "yet", "yield", "you", "young",
  "your", "yourself", "youth", "abandon", "ability", "absence",
  "absolute", "absorb", "abstract", "abundance", "accelerate",
  "accent", "access", "accident", "accomplish", "accurate", "achieve",
  "acknowledge", "acquire", "action", "adapt", "addition", "adequate",
  "admire", "admit", "advance", "adventure", "advice", "advocate",
  "affect", "afford", "agency", "agenda", "agent", "agriculture",
  "aid", "aim", "aircraft", "alarm", "align", "allocate",
  "alternative", "ambition", "amplify", "analyze", "ancient", "angle",
  "animal", "announce", "annual", "anticipate", "anxiety", "apparent",
  "approach", "appropriate", "approve", "argument", "arrange",
  "arrival", "article", "aspect", "assemble", "assert", "assess",
  "assign", "assist", "associate", "assume", "athlete", "atmosphere",
  "attach", "attain", "attempt", "attitude", "attract", "attribute",
  "audience", "authentic", "average", "awareness", "awesome",
  "balance", "barrier", "basic", "behavior", "belief", "belong",
  "benefit", "beverage", "biology", "boundary", "brave", "breathe",
  "brief", "brilliant", "broadcast", "builder", "bulletin", "burden",
  "calculate", "campaign", "capacity", "capture", "care", "carry",
  "case", "catch", "celebrate", "center", "century", "ceremony",
  "chamber", "chance", "change", "character", "charge", "chart",
  "check", "child", "choice", "choose", "church", "circle", "citizen",
  "city", "claim", "class", "clean", "clear", "climb", "close",
  "clothes", "cloud", "club", "coast", "coffee", "cold", "collect",
  "college", "combine", "comfort", "command", "comment", "commit",
  "common", "communicate", "community", "company", "compare",
  "compete", "complain", "complete", "complex", "compute",
  "concentrate", "concept", "concern", "concert", "condition",
  "conflict", "connect", "consider", "consist", "constant",
  "construct", "contact", "contain", "continue", "control",
  "contribute", "convention", "convince", "cook", "coordinate",
  "corporation", "correct", "council", "counsel", "count", "country",
  "couple", "courage", "course", "court", "cover", "create", "credit",
  "crew", "critic", "cross", "crowd", "crucial", "culture", "current",
  "curve", "custom", "damage", "dance", "danger", "dark", "data",
  "date", "daughter", "day", "dead", "deal", "debate", "debt",
  "decide", "declare", "deep", "defend", "define", "degree",
  "deliver", "demand", "department", "depend", "describe", "desire",
  "destroy", "detail", "determine", "develop", "device", "difference",
  "different", "difficult", "dilemma", "dimension", "dinner",
  "direct", "direction", "director", "discover", "discuss", "disease",
  "dismiss", "display", "distance", "distinguish", "distribute",
  "diverse", "divide", "document", "dollar", "domestic", "dominant",
  "double", "doubt", "dream", "drive", "drop", "earn", "earth",
  "easily", "east", "easy", "economic", "educate", "effective",
  "effort", "either", "elect", "electric", "element", "else",
  "embarrass", "emerge", "emergency", "emphasize", "employee",
  "employer", "employment", "encounter", "encourage", "end", "energy",
  "enforce", "engage", "engine", "engineer", "enhance", "enjoy",
  "enormous", "ensure", "enter", "entertain", "entire", "entity",
  "environment", "equal", "equivalent", "escape", "especially",
  "establish", "estimate", "evaluate", "even", "event", "eventually",
  "evidence", "exact", "examine", "example", "exceed", "excellent",
  "except", "exchange", "excuse", "execute", "exercise", "exist",
  "expand", "expect", "experience", "experiment", "expert", "explain",
  "explore", "express", "extend", "extension", "external",
  "extraordinary", "extreme", "face", "facility", "factor", "fail",
  "fair", "faith", "fall", "familiar", "family", "famous",
  "fantastic", "far", "farm", "fashion", "fast", "father", "favor",
  "favorite", "fear", "feature", "federal", "fee", "feel", "female",
  "festival", "few", "field", "fight", "figure", "file", "fill",
  "film", "final", "finance", "find", "fine", "finger", "finish",
  "fire", "firm", "first", "fit", "five", "fix", "flag", "flavor",
  "flight", "float", "floor", "flow", "flower", "focus", "fold",
  "follow", "food", "foot", "force", "foreign", "forest", "forever",
  "forget", "form", "formal", "fortune", "forward", "found", "four",
  "frame", "free", "freedom", "fresh", "friend", "front", "fruit",
  "fuel", "fun", "function", "fund", "funny", "future", "gain",
  "game", "gap", "garage", "garden", "gas", "gather", "general",
  "generate", "generation", "gentle", "genuine", "gesture", "get",
  "gift", "girl", "give", "glass", "goal", "god", "gold", "good",
  "govern", "government", "grace", "grade", "grand", "grant", "grass",
  "great", "green", "ground", "group", "grow", "growth", "guarantee",
  "guard", "guess", "guest", "guide", "guilt", "gun", "guy", "habit",
  "hair", "half", "hall", "hand", "handle", "hang", "happen", "happy",
  "hard", "harm", "hat", "hate", "have", "head", "heal", "health",
  "hear", "heart", "heat", "heavy", "help", "here", "hero", "hey",
  "hide", "high", "highlight", "highway", "hill", "hire",
  "historical", "history", "hit", "hold", "hole", "holiday", "home",
  "honest", "hope", "horizon", "horse", "hospital", "host", "hot",
  "hotel", "hour", "house", "how", "huge", "human", "humor",
  "hundred", "hungry", "hunt", "hurry", "hurt", "husband", "idea",
  "identify", "ignore", "ill", "illegal", "illness", "imagine",
  "impact", "implement", "importance", "important", "impose",
  "impress", "improve", "incentive", "incident", "include", "income",
  "increase", "independence", "influence", "inform", "information",
  "ingredient", "initial", "injury", "innovation", "input", "inside",
  "install", "instance", "instead", "institute", "instruct",
  "insurance", "integrate", "intention", "interaction", "interest",
  "internal", "international", "interview", "introduce", "invest",
  "investigate", "investigation", "invite", "involve", "iron",
  "island", "issue", "jacket", "job", "join", "joint", "journey",
  "judge", "judgment", "jump", "jury", "just", "justice", "keep",
  "key", "kick", "kid", "kill", "kind", "king", "kiss", "kitchen",
  "knee", "knife", "knock", "know", "knowledge", "lab", "labor",
  "lack", "lake", "land", "landscape", "language", "large", "last",
  "late", "later", "laugh", "launch", "law", "lawyer", "lay", "lead",
  "leader", "leadership", "leading", "league", "learn", "least",
  "leather", "leave", "lecture", "left", "leg", "legal", "legend",
  "leisure", "lesson", "letter", "level", "library", "lie", "life",
  "lift", "light", "like", "limit", "line", "link", "list", "listen",
  "literature", "little", "live", "load", "loan", "local", "location",
  "lock", "long", "look", "lose", "loss", "love", "low", "machine",
  "magazine", "mail", "main", "major", "majority", "make", "man",
  "manage", "management", "manager", "manner", "manufacturer", "many",
  "map", "march", "mark", "market", "marketing", "marriage", "master",
  "match", "material", "matter", "may", "maybe", "meal", "mean",
  "measure", "measurement", "meat", "media", "medicine", "medium",
  "meet", "meeting", "member", "membership", "memory", "mention",
  "message", "metal", "method", "middle", "might", "mile", "military",
  "milk", "mind", "mine", "minimum", "minute", "mirror", "miss",
  "mission", "mistake", "mix", "model", "modern", "moment", "money",
  "monitor", "month", "mood", "morning", "most", "mother", "motion",
  "motor", "mountain", "mouse", "mouth", "move", "movement", "movie",
  "much", "music", "muscle", "museum", "music", "mutual", "myth",
  "name", "narrow", "nation", "national", "natural", "nature", "near",
  "necessary", "neck", "need", "negative", "negotiate", "negotiation",
  "neighbor", "neighborhood", "neither", "nervous", "network",
  "never", "new", "news", "newspaper", "next", "nice", "night", "no",
  "nobody", "noise", "nomination", "none", "nor", "normal", "north",
  "nose", "not", "note", "nothing", "notice", "novel", "now",
  "nuclear", "number", "numerous", "obvious", "occasion",
  "occupation", "occur", "ocean", "odd", "off", "offer", "office",
  "officer", "official", "often", "oil", "ok", "old", "on", "once",
  "one", "only", "onto", "open", "operation", "opinion",
  "opportunity", "oppose", "opposite", "option", "or", "order",
  "ordinary", "organization", "organize", "origin", "other", "ought",
  "our", "out", "outcome", "outside", "oven", "over", "overall",
  "own", "owner", "pace", "pack", "package", "page", "pain", "paint",
  "pair", "pale", "pan", "panel", "paper", "parent", "park", "part",
  "participant", "participate", "particular", "particularly",
  "partly", "partner", "party", "pass", "passage", "passenger",
  "passion", "past", "path", "patient", "pattern", "pause", "pay",
  "peace", "peak", "pen", "penalty", "people", "per", "perceive",
  "percentage", "perception", "perfect", "perform", "performance",
  "perhaps", "period", "permanent", "permission", "permit", "person",
  "personal", "perspective", "persuade", "pet", "phase", "philosophy",
  "phone", "photo", "photograph", "phrase", "physical", "piano",
  "pick", "picture", "pie", "piece", "pile", "pilot", "pin", "pipe",
  "pitch", "place", "plan", "plane", "planet", "planning", "plant",
  "plastic", "plate", "platform", "play", "player", "please",
  "pleasure", "plenty", "plot", "plus", "pm", "pocket", "poem",
  "poet", "poetry", "point", "police", "policy", "political",
  "politics", "pool", "poor", "pop", "popular", "population", "port",
  "pose", "position", "positive", "possess", "possession",
  "possibility", "possible", "post", "pot", "potato", "potential",
  "pound", "poverty", "power", "powerful", "practice", "praise",
  "pray", "preach", "precious", "prefer", "preference", "pregnant",
  "preparation", "prepare", "presence", "present", "presentation",
  "preserve", "president", "press", "pressure", "pretend", "pretty",
  "prevent", "previous", "previously", "price", "pride", "priest",
  "primarily", "primary", "prime", "principal", "principle", "print",
  "prior", "priority", "prison", "private", "probably", "problem",
  "procedure", "proceed", "process", "produce", "producer", "product",
  "production", "profession", "professional", "professor", "profile",
  "profit", "program", "progress", "project", "prominent", "promise",
  "promote", "promotion", "prompt", "proof", "proper", "property",
  "proportion", "proposal", "propose", "prospect", "protect",
  "protection", "protein", "protest", "proud", "prove", "provide",
  "provider", "province", "provision", "psychological", "psychology",
  "public", "publication", "publicity", "publish", "pull",
  "punishment", "purchase", "pure", "purpose", "pursue", "pursuit",
  "push", "put", "qualify", "quality", "quantity", "quarter",
  "question", "quick", "quiet", "quietly", "quit", "quite", "quote",
  "race", "racial", "radical", "radio", "rail", "rain", "raise",
  "range", "rank", "rapid", "rare", "rate", "rather", "ratio", "raw",
  "reach", "react", "reaction", "read", "reader", "reading", "ready",
  "real", "reality", "realize", "really", "reason", "reasonable",
  "recall", "receive", "recent", "recently", "recipe", "recognition",
  "recognize", "recommend", "record", "recording", "recover",
  "recovery", "recruit", "red", "reduce", "reduction", "refer",
  "reference", "reflect", "reflection", "reform", "refuse", "regard",
  "regarding", "regardless", "regional", "register", "regret",
  "regular", "regulation", "reject", "relate", "relation",
  "relationship", "relative", "relatively", "relax", "release",
  "relevant", "relief", "religion", "religious", "rely", "remain",
  "remaining", "remark", "remember", "remind", "remote", "remove",
  "repeat", "replace", "reply", "report", "reporter", "represent",
  "representation", "representative", "republican", "reputation",
  "request", "require", "requirement", "research", "researcher",
  "resemble", "reservation", "resident", "resist", "resistance",
  "resolve", "resort", "resource", "respect", "respond", "response",
  "responsibility", "responsible", "rest", "restaurant", "restore",
  "restriction", "result", "retain", "retire", "retirement", "return",
  "reveal", "revenue", "review", "revolution", "rhythm", "rice",
  "rich", "rid", "ride", "rifle", "right", "ring", "rise", "risk",
  "river", "road", "rock", "role", "roll", "romantic", "roof", "room",
  "root", "rope", "rose", "rough", "round", "route", "routine", "row",
  "rub", "rule", "run", "running", "rural", "rush", "russian",
  "sacred", "safe", "safety", "sake", "salad", "salary", "sale",
  "sales", "salt", "same", "sample", "sanction", "sand", "satellite",
  "satisfaction", "satisfy", "sauce", "save", "saving", "say",
  "scale", "scandal", "scan", "scare", "scatter", "scenario", "scene",
  "schedule", "scheme", "scholar", "school", "science", "scientific",
  "scientist", "scope", "score", "scream", "screen", "script", "sea",
  "search", "season", "seat", "second", "secret", "secretary",
  "section", "sector", "secure", "security", "see", "seed", "seek",
  "seem", "segment", "seize", "select", "selection", "self", "sell",
  "senate", "senator", "send", "senior", "sense", "sensitive",
  "sentence", "separate", "sequence", "series", "serious",
  "seriously", "serve", "service", "session", "set", "setting",
  "settle", "settlement", "seven", "several", "severe", "sex",
  "sexual", "shade", "shadow", "shake", "shall", "shape", "share",
  "sharp", "she", "sheet", "shelf", "shell", "shelter", "shift",
  "shine", "ship", "shirt", "shock", "shoe", "shoot", "shop",
  "shopping", "shore", "short", "shortly", "shot", "should",
  "shoulder", "shout", "show", "shower", "shut", "sick", "side",
  "sight", "sign", "signal", "significance", "significant",
  "significantly", "silence", "silly", "silver", "similar",
  "similarly", "simple", "simply", "sin", "since", "sing", "singer",
  "single", "sink", "sir", "sister", "sit", "site", "situation",
  "size", "skill", "skin", "sky", "sleep", "slice", "slide", "slight",
  "slightly", "slip", "slow", "slowly", "small", "smart", "smell",
  "smile", "smoke", "smooth", "snap", "snow", "so", "so-called",
  "soccer", "social", "society", "soft", "software", "soil", "solar",
  "soldier", "solid", "solution", "solve", "some", "somebody",
  "somehow", "someone", "something", "sometimes", "somewhat",
  "somewhere", "son", "song", "soon", "sophisticated", "sorry",
  "sort", "soul", "sound", "soup", "source", "south", "southern",
  "soviet", "space", "spanish", "speak", "speaker", "special",
  "specialist", "species", "specific", "specifically", "speech",
  "speed", "spend", "spending", "spin", "spirit", "spiritual",
  "split", "spokesman", "sport", "spot", "spread", "spring", "square",
  "squeeze", "stability", "stable", "staff", "stage", "stair",
  "stake", "stand", "standard", "standing", "star", "stare", "start",
  "state", "statement", "station", "statistics", "status", "stay",
  "steady", "steal", "steel", "step", "stick", "still", "stir",
  "stock", "stomach", "stone", "stop", "storage", "store", "storm",
  "story", "straight", "strange", "stranger", "strategic", "strategy",
  "stream", "street", "strength", "stress", "stretch", "strike",
  "string", "strip", "stroke", "strong", "strongly", "structure",
  "struggle", "student", "studio", "study", "stuff", "stupid",
  "style", "subject", "submit", "subsequent", "substance",
  "substantial", "succeed", "success", "successful", "successfully",
  "such", "sudden", "suddenly", "sue", "suffer", "sufficient",
  "sugar", "suggest", "suggestion", "suicide", "suit", "summer",
  "summit", "sun", "super", "supply", "support", "supporter",
  "suppose", "supposed", "supreme", "sure", "surely", "surface",
  "surgery", "surprise", "surprised", "surprising", "surprisingly",
  "surround", "survey", "survival", "survive", "survivor", "suspect",
  "suspicion", "suspicious", "swim", "swing", "switch", "symbol",
  "symptom", "system", "table", "tablespoon", "tactic", "tail",
  "take", "tale", "talent", "talk", "tall", "tank", "tap", "tape",
  "target", "task", "taste", "tax", "taxpayer", "tea", "teach",
  "teacher", "teaching", "team", "tear", "technical", "technique",
  "technology", "teen", "teenager", "telephone", "telescope",
  "television", "tell", "temperature", "temporary", "ten", "tend",
  "tendency", "tennis", "tension", "tent", "term", "terms",
  "terrible", "territory", "terror", "terrorism", "terrorist", "test",
  "testify", "testimony", "testing", "text", "than", "thank",
  "thanks", "that", "the", "theater", "their", "them", "theme",
  "themselves", "then", "theory", "therapy", "there", "therefore",
  "these", "they", "thick", "thin", "thing", "think", "thinking",
  "third", "thirty", "this", "those", "though", "thought", "thousand",
  "threat", "threaten", "three", "throat", "through", "throughout",
  "throw", "thus", "ticket", "tie", "tight", "time", "tiny", "tip",
  "tire", "tired", "tissue", "title", "to", "tobacco", "today", "toe",
  "together", "tomorrow", "tone", "tongue", "tonight", "too", "tool",
  "tooth", "top", "topic", "toss", "total", "totally", "touch",
  "tough", "tour", "tourist", "tournament", "toward", "towards",
  "tower", "town", "toy", "trace", "track", "trade", "tradition",
  "traditional", "traffic", "tragedy", "trail", "train", "training",
  "transfer", "transform", "transformation", "transition",
  "translate", "translation", "transmission", "transport",
  "transportation", "trap", "trash", "travel", "treat", "treatment",
  "treaty", "tree", "tremendous", "trend", "trend", "trial", "tribe",
  "trick", "trip", "troop", "trouble", "truck", "true", "truly",
  "trust", "truth", "try", "tube", "tunnel", "turn", "tv", "twelve",
  "twenty", "twice", "twin", "two", "type", "typical", "typically",
  "ugly", "ultimate", "ultimately", "unable", "uncle", "under",
  "undergo", "understand", "understanding", "undertake",
  "unemployment", "unexpected", "unfair", "unfold", "unfortunately",
  "uniform", "union", "unique", "unit", "unite", "unity", "universal",
  "universe", "university", "unknown", "unless", "unlike", "unlikely",
  "until", "unusual", "up", "upon", "upper", "urban", "urge", "us",
  "use", "used", "useful", "user", "usual", "usually", "utility",
  "utilize", "vacation", "vaccine", "valid", "valley", "valuable",
  "value", "variable", "variation", "variety", "various", "vary",
  "vast", "vegetable", "vehicle", "venture", "version", "versus",
  "very", "vessel", "veteran", "via", "victim", "victory", "video",
  "view", "viewer", "village", "violate", "violation", "violence",
  "violent", "virtually", "virtue", "virus", "visible", "vision",
  "visit", "visitor", "visual", "vital", "voice", "volume",
  "volunteer", "vote", "voter", "vs", "vulnerable", "wage", "wait",
  "wake", "walk", "wall", "apple", "banana", "car", "dog", "elephant",
  "fish", "guitar", "house", "ice cream", "jacket", "kite", "lemon",
  "mountain", "notebook", "orange", "penguin", "queen", "rabbit",
  "sun", "tree", "umbrella", "violin", "watermelon", "xylophone",
  "zebra", "airplane", "bicycle", "cat", "dolphin", "eagle", "flower",
  "giraffe", "hat", "igloo", "jellyfish", "kangaroo", "laptop",
  "mango", "night", "ocean", "piano", "quill", "rose", "snake",
  "tiger", "unicorn", "vase", "whale", "xylophone", "yacht",
  "zeppelin", "ball", "candle", "diamond", "elephant", "fire",
  "guitar", "horse", "igloo", "jungle", "kite", "lemon", "moon",
  "ninja", "oasis", "parrot", "quokka", "rainbow", "star", "turtle",
  "umbrella", "volcano", "waterfall", "x-ray", "yeti", "zebra",
  "avocado", "butterfly", "chocolate", "dinosaur", "eggplant",
  "flamingo", "giraffe", "hamburger", "ice cream", "jellybean",
  "kiwi", "leopard", "mushroom", "narwhal", "octopus", "penguin",
  "quail", "raccoon", "sunflower", "tiger", "unicorn", "vampire",
  "watermelon", "xylophone", "yak", "zeppelin", "chocolate",
  "dolphin", "elephant", "flamingo", "giraffe", "hamburger",
  "ice cream", "jellybean", "kiwi", "leopard", "mushroom", "narwhal",
  "octopus", "penguin", "quail", "raccoon", "sunflower", "tiger",
  "unicorn", "vampire", "watermelon", "xylophone", "yak", "zeppelin",
  "avocado", "butterfly", "caterpillar", "dandelion", "elephant",
  "firefly", "gazelle", "hummingbird", "igloo", "jigsaw", "koala",
  "llama", "mandolin", "narwhal", "octopus", "peacock", "quokka",
  "rattlesnake", "saxophone", "toucan", "umbrella", "vulture",
  "wombat", "x-ray", "yacht", "zebra", "antelope", "blueberry",
  "cheetah", "dolphin", "elephant", "falcon", "giraffe", "hedgehog",
  "iguana", "jackal", "kangaroo", "lemur", "mongoose", "newt",
  "opossum", "peacock", "quokka", "rhinoceros", "scorpion",
  "tarantula", "unicorn", "vulture", "wallaby", "x-ray", "yak",
  "zeppelin", "alpaca", "bison", "cockatoo", "dolphin", "elephant",
  "fennec", "giraffe", "hedgehog", "iguana", "jackal", "kangaroo",
  "lemur", "mongoose", "newt", "opossum", "peacock", "quokka",
  "rhinoceros", "scorpion", "tarantula", "unicorn", "vulture",
  "wallaby", "x-ray", "yak", "zeppelin", "table", "guitar", "tiger",
  "kangaroo", "butterfly", "elephant", "orange", "jacket", "ocean",
  "waterfall", "candle", "mountain", "umbrella", "keyboard", "lemon",
  "violin", "diamond", "dolphin", "parrot", "zebra", "sunflower",
  "cupcake", "penguin", "rainbow", "bicycle", "fireplace", "giraffe",
  "night", "volcano", "whale", "cat", "moon", "vase", "carrot",
  "oasis", "snake", "quill", "chocolate", "airplane", "hat",
  "octopus", "ice cream", "jungle", "violin", "elephant", "beach",
  "elephant", "apple", "tree", "fox", "guitar", "house", "river",
  "star", "mushroom", "lion", "ship", "island", "kite", "tulip",
  "notebook", "hammer", "rocket", "lighthouse", "tornado", "piano",
  "skateboard", "unicorn", "castle", "sandcastle", "penguin",
  "sunrise", "garden", "mailbox", "robot", "helicopter", "dragon",
  "zoo", "lake", "butterfly", "hamburger", "giraffe", "firework",
  "turtle", "laptop", "jellyfish", "football", "camera", "raindrop",
  "raincoat", "suitcase", "umbrella", "giraffe", "whisper",
  "moonlight", "fountain", "dragonfly", "sandcastle", "caterpillar",
  "treasure", "quokka", "waterfall", "kangaroo", "butterfly",
  "elephant", "breeze", "carousel", "jellybean", "skateboard",
  "parrot", "rainbow", "zeppelin", "sunflower", "dolphin",
  "fireplace", "tiger", "sunset", "volcano", "candle", "harmony",
  "starlight", "lighthouse", "keyboard", "oasis", "guitar", "beach",
  "chocolate", "marathon", "shipwreck", "mailbox", "orchestra",
  "octopus", "carousel", "butterfly", "elephant", "apple", "tree",
  "garden", "river", "firework", "whale", "tornado", "moon", "jacket",
  "hurricane", "vase", "robot", "helicopter", "castle", "mountain",
  "hamster", "unicorn", "paradise", "piano", "watermelon",
  "saxophone", "beach", "penguin", "sunrise", "jungle", "mailbox",
  "raindrop", "carousel", "rocket", "lighthouse", "tulip", "notebook",
  "hammer", "dragon", "zoo", "lake", "butterfly", "hamburger",
  "giraffe", "firework", "turtle", "laptop", "jellyfish", "football",
  "camera", "raindrop", "raincoat", "dragonfly", "dolphin", "koala",
  "hedgehog", "peacock", "zeppelin", "wombat", "quokka", "toucan",
  "rhinoceros", "iguana", "parrot", "sunflower", "blueberry", "koala",
  "octopus", "rattlesnake", "xylophone", "moonlight", "dolphin",
  "firefly", "whisper", "dragonfly", "caterpillar", "treasure",
  "candle", "carousel", "chocolate", "elephant", "giraffe", "guitar",
  "waterfall", "whale", "sunrise", "rainbow", "umbrella", "fountain",
  "marathon", "quill", "mailbox", "zeppelin", "zebra", "sandcastle",
  "carousel", "lighthouse", "parrot", "watermelon", "beach",
  "kangaroo", "jellybean", "garden", "firework", "robot", "dragon",
  "moon", "tiger", "butterfly", "piano", "ocean", "guitar",
  "starlight", "vase", "jungle", "helicopter", "rocket", "lake",
  "mountain", "hamster", "unicorn", "paradise", "orchestra",
  "notebook", "tornado", "jacket", "turtle", "apple", "shipwreck",
  "river", "harmony", "mailbox", "tree", "hurricane", "camera",
  "laptop", "saxophone", "football", "raincoat", "suitcase", "beach",
  "carousel", "dragonfly", "whale", "koala", "jellyfish", "hedgehog",
  "butterfly", "zeppelin", "elephant", "tulip", "peacock", "breeze",
  "giraffe", "unicorn", "sunshine", "butterfly", "whisper", "giraffe",
  "zeppelin", "treasure", "marathon", "carousel", "whale",
  "jellybean", "dolphin", "moonlight", "parrot", "watermelon",
  "guitar", "breeze", "robot", "firework", "beach", "orchestra",
  "zebra", "river", "mailbox", "paradise", "jungle", "candle",
  "octopus", "tiger", "lighthouse", "garden", "chocolate", "sunset",
  "rainbow", "unicorn", "dragonfly", "harmony", "xylophone",
  "mountain", "ocean", "sunrise", "vase", "koala", "lake", "quokka",
  "piano", "rocket", "umbrella", "castle", "notebook", "firefly",
  "shipwreck", "zeppelin", "hurricane", "rhinoceros", "iguana",
  "butterfly", "turtle", "dragon", "jacket", "moon", "zeppelin",
  "guitar", "wombat", "camera", "saxophone", "laptop", "waterfall",
  "blueberry", "football", "raincoat", "zeppelin", "caterpillar",
  "whale", "tornado", "carousel", "zeppelin", "tree", "zeppelin",
  "zeppelin", "zeppelin", "zeppelin", "sunshine", "butterfly",
  "whisper", "giraffe", "zeppelin", "treasure", "marathon",
  "carousel", "whale", "jellybean", "dolphin", "moonlight", "parrot",
  "watermelon", "guitar", "breeze", "robot", "firework", "beach",
  "orchestra", "zebra", "river", "mailbox", "paradise", "jungle",
  "candle", "octopus", "tiger", "lighthouse", "garden", "chocolate",
  "sunset", "rainbow", "unicorn", "dragonfly", "harmony", "xylophone",
  "mountain", "ocean", "sunrise", "vase", "koala", "lake", "quokka",
  "piano", "rocket", "umbrella", "castle", "notebook", "firefly",
  "shipwreck", "hurricane", "rhinoceros", "iguana", "turtle",
  "dragon", "jacket", "moon", "wombat", "camera", "saxophone",
  "laptop", "waterfall", "blueberry", "football", "raincoat",
  "caterpillar", "tornado", "tree", "sunflower", "kangaroo",
  "sandcastle", "zeppelin", "bison", "mushroom", "oasis", "peacock",
  "volcano", "whistle", "quill", "saxophone", "hammer", "falcon",
  "robot", "fountain", "unicorn", "butterfly", "butterfly", "octopus",
  "sunflower", "elephant", "whisper", "jellybean", "sunshine",
  "butterfly", "whisper", "giraffe", "zeppelin", "treasure",
  "marathon", "carousel", "whale", "jellybean", "dolphin",
  "moonlight", "parrot", "watermelon", "guitar", "breeze", "robot",
  "firework", "beach", "orchestra", "zebra", "river", "mailbox",
  "paradise", "jungle", "candle", "octopus", "tiger", "lighthouse",
  "garden", "chocolate", "sunset", "rainbow", "unicorn", "dragonfly",
  "harmony", "xylophone", "mountain", "ocean", "sunrise", "vase",
  "koala", "lake", "quokka", "piano", "rocket", "umbrella", "castle",
  "notebook", "firefly", "shipwreck", "hurricane", "rhinoceros",
  "iguana", "turtle", "dragon", "jacket", "moon", "wombat", "camera",
  "saxophone", "laptop", "waterfall", "blueberry", "football",
  "raincoat", "caterpillar", "tornado", "tree", "sunflower",
  "kangaroo", "sandcastle", "bison", "mushroom", "oasis", "peacock",
  "volcano", "whistle", "quill", "saxophone", "hammer", "falcon",
  "robot", "fountain", "zeppelin", "butterfly", "octopus",
  "sunflower", "elephant", "whisper", "jellybean", "penguin", "night",
  "zeppelin", "ocean", "lighthouse", "quokka", "zeppelin", "zeppelin",
  "apple", "sunshine", "butterfly", "whisper", "giraffe", "zeppelin",
  "treasure", "marathon", "carousel", "whale", "jellybean", "dolphin",
  "moonlight", "parrot", "watermelon", "guitar", "breeze", "robot",
  "firework", "beach", "orchestra", "zebra", "river", "mailbox",
  "paradise", "jungle", "candle", "octopus", "tiger", "lighthouse",
  "garden", "chocolate", "sunset", "rainbow", "unicorn", "dragonfly",
  "harmony", "xylophone", "mountain", "ocean", "sunrise", "vase",
  "koala", "lake", "quokka", "piano", "rocket", "umbrella", "castle",
  "notebook", "firefly", "shipwreck", "hurricane", "rhinoceros",
  "iguana", "turtle", "dragon", "jacket", "moon", "wombat", "camera",
  "saxophone", "laptop", "waterfall", "blueberry", "football",
  "raincoat", "caterpillar", "tornado", "tree", "sunflower",
  "kangaroo", "sandcastle", "bison", "mushroom", "oasis", "peacock",
  "volcano", "whistle", "quill", "saxophone", "hammer", "falcon",
  "robot", "fountain", "zeppelin", "butterfly", "octopus",
  "sunflower", "elephant", "whisper", "jellybean", "penguin", "night",
  "zeppelin", "ocean", "lighthouse", "quokka", "zeppelin", "zeppelin",
  "apple", "sunshine", "butterfly", "whisper", "giraffe", "zeppelin",
  "treasure", "marathon", "carousel", "whale", "jellybean", "dolphin",
  "moonlight", "parrot", "watermelon", "guitar", "breeze", "robot",
  "firework", "beach", "orchestra", "zebra", "river", "mailbox",
  "paradise", "jungle", "candle", "octopus", "tiger", "lighthouse",
  "garden", "chocolate", "sunset", "rainbow", "unicorn", "dragonfly",
  "harmony", "xylophone", "mountain", "ocean", "sunrise", "vase",
  "koala", "lake", "quokka", "piano", "rocket", "umbrella", "castle",
  "notebook", "firefly", "shipwreck", "hurricane", "rhinoceros",
  "iguana", "turtle", "dragon", "jacket", "moon", "wombat", "camera",
  "saxophone", "laptop", "waterfall", "blueberry", "football",
  "raincoat", "caterpillar", "tornado", "tree", "sunflower",
  "kangaroo", "sandcastle", "bison", "mushroom", "oasis", "peacock",
  "volcano", "whistle", "quill", "saxophone", "hammer", "falcon",
  "robot", "fountain", "zeppelin", "butterfly", "octopus",
  "sunflower", "elephant", "whisper", "jellybean", "penguin", "night",
  "ocean", "lighthouse", "quokka", "apple", "abundant", "accommodate",
  "accurate", "achieve", "acknowledge", "acquire", "adapt", "add",
  "address", "adequate", "admire", "admit", "adopt", "advance",
  "advise", "affect", "afford", "after", "again", "against", "age",
  "agent", "agree", "air", "alarm", "alcohol", "alike", "all",
  "allow", "almost", "alone", "along", "already", "also", "although",
  "always", "amount", "analyse", "analyze", "ancient", "and", "anger",
  "animal", "announce", "annual", "another", "answer", "any", "apart",
  "apartment", "apparent", "appear", "appreciate", "approach",
  "appropriate", "approve", "argue", "arise", "arm", "army", "around",
  "arrange", "arrive", "art", "article", "artificial", "artist", "as",
  "ask", "aspect", "assemble", "assess", "asset", "assist", "assume",
  "assure", "astonish", "attach", "attack", "attempt", "attend",
  "attitude", "attract", "audience", "audit", "author", "automatic",
  "available", "aware", "away", "baby", "back", "bad", "bag",
  "balance", "ball", "band", "bank", "bar", "bare", "base", "basic",
  "basis", "basket", "bath", "battery", "battle", "be", "bear",
  "beat", "beautiful", "because", "become", "bed", "bedroom", "beer",
  "before", "beg", "begin", "behave", "behind", "believe", "bell",
  "belong", "below", "belt", "bend", "beneath", "benefit", "beside",
  "best", "better", "between", "beyond", "bicycle", "bid", "big",
  "bike", "bill", "bind", "bird", "birth", "bit", "bite", "black",
  "blade", "blame", "blank", "block", "blood", "blow", "blue",
  "board", "boast", "boat", "body", "boil", "bold", "bone", "book",
  "boot", "border", "born", "borrow", "boss", "both", "bother",
  "bottle", "bottom", "boundary", "bowl", "box", "boy", "brain",
  "branch", "brave", "bread", "break", "breakfast", "breath", "brick",
  "bridge", "brief", "bright", "bring", "broad", "broken", "brother",
  "brown", "brush", "bucket", "budget", "build", "bulb", "bulk",
  "bullet", "bunch", "burden", "burn", "burst", "bury", "bus", "bush",
  "business", "busy", "but", "butter", "button", "buy", "by", "cable",
  "cake", "calculate", "call", "calm", "camera", "camp", "can",
  "cancel", "cancer", "candle", "candy", "canvas", "cap", "capable",
  "capital", "captain", "capture", "car", "carbon", "card", "care",
  "career", "careful", "carry", "case", "cash", "cast", "castle",
  "cat", "catch", "category", "cause", "caution", "cave", "CD",
  "cease", "ceiling", "celebrate", "cell", "cement", "centre",
  "century", "ceremony", "certain", "chain", "chair", "challenge",
  "champion", "chance", "change", "channel", "chapter", "character",
  "charge", "charm", "chart", "chase", "cheap", "cheat", "check",
  "cheek", "cheer", "cheese", "chemical", "chest", "chicken", "chief",
  "child", "choice", "choose", "chop", "church", "circle", "circuit",
  "circumstance", "cite", "citizen", "city", "civil", "claim", "clap",
  "class", "clause", "clean", "clear", "clerk", "clever", "click",
  "client", "climate", "climb", "clinic", "clock", "close", "cloth",
  "cloud", "club", "clue", "coach", "coal", "coarse", "coast", "coat",
  "code", "coffee", "coin", "cold", "collar", "collect", "college",
  "colon", "aback", "abase", "abate", "abbey", "abbey", "abbot",
  "abbreviate", "abduct", "aberration", "abet", "abhor", "abide",
  "abiding", "ability", "abject", "abjure", "ablate", "ablaze",
  "able", "ablution", "abnegate", "abnormal", "aboard", "abode",
  "abolish", "abominable", "abominate", "aboriginal", "abortion",
  "abound", "about", "above", "abrasive", "abreast", "abridge",
  "abroad", "abrogate", "abrupt", "abscess", "abscond", "absence",
  "absent", "absolute", "absolve", "absorb", "abstain", "abstinence",
  "abstract", "absurd", "abundant", "abuse", "abusive", "abut",
  "abyss", "academic", "academy", "accede", "accelerate", "accent",
  "accentuate", "accept", "acceptable", "access", "accessory",
  "accident", "accidental", "acclaim", "acclamation", "accommodate",
  "accompaniment", "accompany", "accomplish", "accord", "according",
  "accordingly", "accost", "account", "accountable", "accountant",
  "accredit", "accretion", "accumulate", "accurate", "accursed",
  "accuse", "accustom", "acerbic", "acetate", "achieve",
  "achievement", "acid", "acidic", "acknowledge", "acme", "acne",
  "acoustic", "acquaint", "acquaintance", "acquiesce", "acquire",
  "acquit", "acre", "acrid", "acrimonious", "acrobat", "acronym",
  "across", "act", "action", "activate", "active", "activist",
  "actor", "actress", "actual", "actuate", "acute", "adage", "adapt",
  "adaptable", "adapter", "add", "addict", "addiction", "additive",
  "address", "adept", "adequate", "adhere", "adherent", "adhesive",
  "adjacent", "adjourn", "adjudge", "adjudicate", "adjust",
  "administer", "admiral", "admire", "admission", "admit",
  "admittance", "admonish", "ado", "adobe", "adolescent", "adopt",
  "adorable", "adorn", "adrenal", "adrift", "adroit", "adult",
  "adulterate", "adultery", "advance", "advantage", "advent",
  "adventure", "adverb", "adversary", "adverse", "advert",
  "advertise", "advertisement", "advice", "advise", "advocate",
  "aerial", "aerobic", "aerosol", "aesthetic", "afar", "affable",
  "affair", "affect", "affection", "affidavit", "affiliate",
  "affinity", "affirm", "affix", "afflict", "afford", "affront",
  "afraid", "aft", "after", "afternoon", "afterthought", "again",
  "against", "age", "aged", "agency", "agenda", "agent", "aggravate",
  "aggregate", "aggression", "aggressive", "aghast", "agile",
  "agitate", "agnostic", "agonize", "agony", "agree", "agreeable",
  "agreement", "agriculture", "ahead", "aid", "ail", "ailment", "aim",
  "air", "aircraft", "airfare", "airline", "airport", "airy", "ajar",
  "akin", "alarm", "alarmist", "albeit", "album", "alcohol",
  "alcoholic", "alert", "algebra", "alien", "alienate", "alight",
  "align", "alike", "aliment", "alimony", "alive", "alkali",
  "alkaline", "all", "allay", "allege", "allegiance", "allegory",
  "allergic", "allergy", "alleviate", "alley", "alliance",
  "alligator", "allocate", "allot", "allow", "allowance", "alloy",
  "allure", "ally", "almighty", "almost", "aloe", "aloft", "alone",
  "along", "alongside", "aloof", "aloud", "alphabet", "already",
  "also", "altar", "alter", "alteration", "apple", "banana", "cat",
  "dog", "elephant", "fish", "goat", "horse", "igloo", "jellyfish",
  "kangaroo", "lion", "monkey", "narwhal", "octopus", "panda",
  "quail", "rhino", "snake", "turtle", "umbrella", "violin",
  "watermelon", "xylophone", "yak", "zebra", "aardvark", "antelope",
  "armadillo", "baboon", "badger", "bat", "beaver", "bison", "boar",
  "buffalo", "camel", "capybara", "cassowary", "cheetah",
  "chimpanzee", "chinchilla", "cobra", "condor", "coyote",
  "crocodile", "deer", "dingo", "dolphin", "donkey", "dromedary",
  "duck", "eagle", "echidna", "elk", "emu", "ferret", "flamingo",
  "fox", "gazelle", "giraffe", "gnu", "gorilla", "grizzly", "hamster",
  "hippopotamus", "hyena", "jackal", "jaguar", "kangaroo", "koala",
  "komodo dragon", "leopard", "llama", "manatee", "meerkat", "moose",
  "narwhal", "orangutan", "ostrich", "otter", "panda", "panther",
  "peacock", "pelican", "penguin", "pheasant", "pig", "polar bear",
  "porcupine", "prairie dog", "puma", "python", "raccoon",
  "rhinoceros", "salamander", "sea lion", "seal", "sheep", "skunk",
  "sloth", "snake", "snow leopard", "sparrow", "spider monkey",
  "squid", "squirrel", "swan", "tapir", "tiger", "turtle", "unicorn",
  "vampire bat", "walrus", "warthog", "weasel", "whale", "wolverine",
  "wombat", "yak", "zebra", "apple", "banana", "cat", "dog",
  "elephant", "fish", "grape", "hat", "ice cream", "jacket", "kite",
  "lemon", "mango", "nut", "orange", "pear", "quilt", "rabbit",
  "snake", "turtle", "umbrella", "vanilla", "watermelon", "xylophone",
  "zebra", "acorn", "butterfly", "candle", "dolphin", "elephant",
  "feather", "giraffe", "hamburger", "igloo", "jellyfish", "kangaroo",
  "leopard", "mountain", "noodle", "octopus", "penguin", "quokka",
  "raccoon", "squirrel", "tiger", "umbrella", "volcano", "walrus",
  "xylophone", "yacht", "zeppelin", "ant", "bee", "caterpillar",
  "dandelion", "eagle", "flamingo", "gazelle", "hedgehog", "iguana",
  "jackal", "koala", "lemur", "mongoose", "narwhal", "ostrich",
  "peacock", "quail", "rattlesnake", "scorpion", "toucan", "unicorn",
  "vulture", "wombat", "x-ray", "yak", "zebra", "alpaca", "bison",
  "cheetah", "dalmatian", "elephant", "fox", "giraffe", "hamster",
  "iguana", "jaguar", "kangaroo", "lemur", "meerkat", "newt",
  "opossum", "panda", "quokka", "rhinoceros", "sloth", "toucan",
  "unicorn", "vulture", "weasel", "x-ray", "yak", "zeppelin", "apple",
  "banana", "cat", "dog", "elephant", "fish", "giraffe",
  "hippopotamus", "iguana", "jaguar", "kangaroo", "lion", "monkey",
  "narwhal", "octopus", "panda", "quokka", "rhinoceros", "snake",
  "tiger", "unicorn", "vampire", "walrus", "xylophone", "zebra",
  "aardvark", "albatross", "antelope", "armadillo", "baboon",
  "badger", "bat", "beaver", "bison", "boar", "bobcat", "buffalo",
  "camel", "capybara", "caribou", "cassowary", "cheetah",
  "chimpanzee", "chinchilla", "cobra", "cockatoo", "condor", "cougar",
  "coyote", "crocodile", "crow", "deer", "dingo", "dolphin", "donkey",
  "dragonfly", "duck", "eagle", "echidna", "elk", "emu", "ferret",
  "flamingo", "fly", "fox", "frog", "gazelle", "gecko", "gerbil",
  "gibbon", "gnu", "goat", "gorilla", "grizzly bear", "guinea pig",
  "hamster", "hedgehog", "hippopotamus", "hyena", "ibex", "iguana",
  "impala", "jackal", "jaguar", "jellyfish", "kangaroo", "koala",
  "komodo dragon", "koala", "lemur", "leopard", "lion", "llama",
  "lynx", "macaw", "magpie", "mandrill", "manatee", "marmot",
  "meerkat", "mink", "mole", "mongoose", "moose", "mountain goat",
  "mouse", "mule", "narwhal", "newt", "ocelot", "octopus", "opossum",
  "orangutan", "oryx", "otter", "panda", "panther", "peacock",
  "pelican", "penguin", "pheasant", "pig", "platypus", "polar bear",
  "porcupine", "possum", "prairie dog", "puma", "quokka", "raccoon",
  "rat", "raven", "reindeer", "rhinoceros", "robin", "rooster",
  "salamander", "sand dollar", "scorpion", "sea lion", "sea turtle",
  "serval", "shark", "sheep", "skunk", "sloth", "snake",
  "snow leopard", "spider", "squid", "squirrel", "stork", "swan",
  "tapir", "tarantula", "tiger", "toad", "toucan", "turtle",
  "wallaby", "walrus", "warthog", "weasel", "whale", "wolverine",
  "wombat", "zebra", "jacket", "kite", "lemon", "mango", "nut",
  "orange", "pear", "quilt", "rabbit", "snake", "turtle", "umbrella",
  "vanilla", "watermelon", "xylophone", "zebra", "acorn", "butterfly",
  "candle", "dolphin", "elephant", "feather", "giraffe", "hamburger",
  "igloo", "jellyfish", "kangaroo", "leopard", "mountain", "noodle",
  "octopus", "penguin", "quokka", "raccoon", "squirrel", "tiger",
  "umbrella", "volcano", "walrus", "xylophone", "yacht", "zeppelin",
  "ant", "bee", "caterpillar", "dandelion", "eagle", "flamingo",
  "gazelle", "hedgehog", "iguana", "jackal", "koala", "lemur",
  "mongoose", "narwhal", "ostrich", "peacock", "quail", "rattlesnake",
  "scorpion", "toucan", "unicorn", "vulture", "wombat", "x-ray",
  "yak", "zebra", "alpaca", "bison", "cheetah", "dalmatian",
  "elephant", "fox", "giraffe", "hamster", "iguana", "jaguar",
  "kangaroo", "lemur", "meerkat", "newt", "opossum", "panda",
  "quokka", "rhinoceros", "sloth", "toucan", "unicorn", "vulture",
  "weasel", "x-ray", "yak", "aardvark", "aback", "abashed", "abbey",
  "abbot", "abbreviate", "abdication", "abdomen", "aberration",
  "abet", "abhor", "abide", "abject", "ablaze", "able", "ablution",
  "abnormal", "abode", "abolish", "abominable", "aboriginal",
  "abortion", "abrasive", "abrupt", "abscess", "abscond", "absence",
  "absent", "absolute", "absolve", "absorb", "abstain", "absurd",
  "abundance", "abuse", "abut", "abyss", "acacia", "academy",
  "accelerate", "accent", "accept", "access", "accessory", "accident",
  "acclaim", "acclamation", "acclimate", "accommodate", "accompany",
  "accomplice", "accomplish", "accord", "accordion", "accost",
  "account", "accoutrements", "accredit", "accrue", "accumulate",
  "accurate", "accursed", "accusation", "accuse", "accustom",
  "acerbic", "acetate", "ache", "achieve", "acid", "acknowledge",
  "acme", "acorn", "acoustic", "acquaint", "acquiesce", "acquire",
  "acquit", "acre", "acrimonious", "acrobat", "acronym", "acrylic",
  "act", "action", "activate", "active", "activist", "actor",
  "actress", "actual", "actuate", "acumen", "acute", "adage",
  "adamant", "adapt", "add", "addendum", "addict", "addition",
  "additive", "address", "adequate", "adhere", "adjacent",
  "adjective", "adjourn", "adjudge", "adjunct", "adjust", "adjutant",
  "administer", "admirable", "admiral", "admire", "admission",
  "admit", "admonition", "ado", "adobe", "adolescent", "adopt",
  "adorable", "adorn", "adrenal", "adroit", "adulate", "adult",
  "adulterate", "adultery", "advance", "advantage", "advent",
  "adventure", "adverb", "adversary", "adverse", "advert",
  "advertise", "advice", "advise", "advocate", "adze", "aegis",
  "aerial", "aerobic", "aerosol", "aesthetic", "affable", "affair",
  "affect", "affection", "affidavit", "affiliate", "affinity",
  "affirm", "affix", "afflict", "afford", "affront", "aflame",
  "afloat", "afoot", "afraid", "aftermath", "afternoon", "again",
  "against", "age", "agency", "agenda", "agent", "aggravate",
  "aggregate", "aggress", "aggressor", "aghast", "agile", "agitate",
  "agnostic", "agonize", "agony", "agree", "agreeable", "agreement",
  "agriculture", "aground", "ague", "ahead", "aid", "ail", "aim",
  "air", "aircraft", "airport", "airy", "akin", "alabaster", "alarm",
  "albeit", "album", "alcohol", "alder", "alert", "algae", "alias",
  "alien", "alienate", "alight", "align", "alike", "aliment",
  "alimony", "alive", "alkali", "all", "allege", "allegiance",
  "allegory", "allergic", "alleviate", "alley", "alliance",
  "alligator", "allocate", "allot", "allow", "alloy", "allure",
  "ally", "almanac", "almighty", "almost", "aloe", "aloft", "alone",
  "along", "aloof", "aloud", "alphabet", "already", "also", "altar",
  "alter", "altercation", "alternate", "although", "altitude", "alto",
  "altogether", "always", "amass", "amateur", "amaze", "ambassador",
  "amber", "ambidextrous", "ambience", "ambiguous", "ambition",
  "ambitious", "amble", "ambrosia", "ambulance", "ambush",
  "ameliorate", "amen", "amiable", "ammunition", "amnesia", "amnesty",
  "amoeba", "among", "amorous", "amorphous", "amphibian",
  "amphitheater", "ample", "amplify", "amputate", "amulet",
  "anachronism", "anaconda", "ancestors", "anchor", "anchovy",
  "ancient", "anecdote", "anemone", "anesthesia", "anew", "angel",
  "anger", "angina", "angle", "angular", "anguish", "animal",
  "animate", "animosity", "ankle", "annex", "annihilate",
  "anniversary", "announce", "annoy", "annual", "annul", "anode",
  "anomaly", "anonymous", "antagonize", "antecedent", "antenna",
  "anterior", "antique", "antiquity", "anxiety", "any", "apart",
  "apartment", "apathetic", "ape", "aperture", "apex", "aphorism",
  "apiary", "apocalypse", "apology", "apostle", "apparatus",
  "apparel", "apparent", "apparition", "appeal", "appear", "appease",
  "appetite", "applaud", "appliance", "applicable", "appreciate",
  "apprehend", "apprentice", "approach", "appropriate", "approval",
  "approximate", "apricot", "apron", "apt", "aquamarine", "aquarium",
  "aquatic", "aqueduct", "arbitrary", "arbitrator", "arc", "arcade",
  "arch", "archaeology", "archipelago", "architect", "archive",
  "arctic", "ardent", "arduous", "arena", "argue", "arid",
  "aristocracy", "arithmetic", "ark", "armadillo", "armature",
  "aroma", "aromatic", "array", "arrest", "arrival", "arrogant",
  "arrow", "arsenal", "arson", "art", "artery", "artisan", "artwork",
  "ascend", "ascertain", "ascetic", "ascribe", "ash", "ashen",
  "ashore", "ashtray", "aside", "asinine", "ask", "askew", "asleep",
  "aspect", "asphalt", "aspire", "ass", "assail", "assassin",
  "assault", "assemble", "assembly", "assent", "assert", "assess",
  "asset", "assign", "assimilate", "assist", "associate",
  "assortment", "assume", "assurance", "asterisk", "astonish",
  "astound", "astral", "astronaut", "astronomy", "asylum", "at",
  "atheist", "athlete", "athletic", "atlas", "atmosphere", "atom",
  "atomic", "atrocious", "attach", "attack", "attain", "attempt",
  "attend", "attention", "attentive", "attest", "attic", "attire",
  "attitude", "attorney", "attract", "attribute", "audacious",
  "audacity", "audible", "audience", "audit", "auditor", "augment",
  "august", "aunt", "auspicious", "authentic", "author",
  "authoritative", "authority", "authorization", "auto",
  "autobiography", "autograph", "automate", "automobile",
  "autonomous", "autumn", "auxiliary", "avail", "avalanche",
  "avarice", "avenge", "avenue", "average", "avert", "aviary", "avid",
  "avocado", "avoid", "await", "awake", "award", "aware", "awe",
  "awkward", "awning", "ax", "axiom", "axis", "axle", "Ayatollah",
  "azalea", "azure", "babbling", "baboon", "baby", "bachelor", "back",
  "backbone", "background", "backing", "backward", "bacon",
  "bacteria", "badge", "badger", "baffle", "bag", "baggage", "baggy",
  "bagpipe", "bail", "bait", "bake", "bakery", "balance", "balcony",
  "bald", "ballad", "ballast", "ballet", "balloon", "ballot",
  "bamboo", "ban", "banana", "band", "bandage", "bandit", "banish",
  "banister", "bank", "bankrupt", "banner", "aardvark", "abacus",
  "aback", "abbey", "abbey road", "abbreviation", "abduction",
  "aberration", "abhorrent", "abide", "ability", "abject", "ablaze",
  "able", "abnormal", "aboard", "abode", "abolish", "abomination",
  "aboriginal", "abort", "abound", "about", "above", "abrasive",
  "abrupt", "abscess", "absence", "absent", "absent-minded",
  "absolute", "absorb", "abstain", "absurd", "abundance", "abuse",
  "abusive", "abyss", "acacia", "academy", "accelerate", "accent",
  "accept", "acceptable", "access", "accessory", "accident",
  "acclaimed", "accommodate", "accompany", "accomplish", "accord",
  "accordingly", "accordion", "accost", "account", "accountable",
  "accredited", "accumulate", "accurate", "accursed", "accuse",
  "accustom", "ache", "achieve", "acid", "acidic", "acknowledge",
  "acme", "acoustic", "acquaint", "acquainted", "acquire", "acquit",
  "acre", "acrobat", "across", "act", "action", "activate", "active",
  "activist", "actor", "actress", "actual", "acupuncture", "acute",
  "adage", "adapt", "adaptable", "add", "addiction", "additive",
  "address", "adequate", "adhere", "adjacent", "adjective", "adjourn",
  "adjudge", "adjudicate", "adjust", "adjutant", "administer",
  "admirable", "admiral", "admire", "admission", "admit",
  "admittance", "admonish", "ado", "adopt", "adorable", "adorn",
  "adrift", "adult", "adulterate", "advance", "advantage", "advent",
  "adventure", "adventurous", "adverb", "adversary", "adverse",
  "advert", "advertise", "advertisement", "advice", "advise",
  "adviser", "advocate", "aerial", "aerobics", "aerospace",
  "aesthetic", "afar", "affair", "affect", "affection", "affidavit",
  "affiliate", "affirm", "affix", "afflict", "afford", "affront",
  "afloat", "afraid", "African", "after", "afternoon", "afterthought",
  "again", "against", "age", "aged", "agency", "agenda", "agent",
  "aggressive", "agitate", "ago", "agony", "agree", "agreement",
  "agriculture", "ahead", "aid", "ail", "ailment", "aim", "air",
  "aircraft", "airfare", "airline", "airport", "airy", "aisle",
  "alarm", "alas", "albeit", "album", "alcohol", "alcoholic", "alert",
  "algae", "algebra", "algorithm", "alias", "alien", "align", "alike",
  "alimentary", "alive", "alkali", "all", "allege", "allegiance",
  "allegory", "allergic", "allergy", "alleviate", "alley", "alliance",
  "alligator", "allocate", "allow", "allowance", "alloy", "allure",
  "ally", "almanac", "almighty", "almost", "aloe", "aloft", "alone",
  "along", "alongside", "aloud", "alphabet", "already", "also",
  "altar", "alter", "alteration", "alternative", "although",
  "altitude", "alto", "always", "amaze", "ambassador", "amber",
  "ambience", "ambiguous", "ambition", "ambitious", "ambulance",
  "ambush", "amen", "amend", "amenity", "American", "amicable",
  "amid", "amidst", "amiss", "ammonia", "ammunition", "amnesty",
  "among", "amongst", "amount", "amphibian", "amphibious",
  "amphitheatre", "ample", "amplify", "amusement", "anaconda",
  "anaesthetic", "anagram", "analgesic", "analogous", "analyse",
  "analysis", "analyst", "anarchist", "abrasive", "abrupt", "accede",
  "acclaim", "acclimate", "accolade", "accommodate", "accompaniment",
  "accomplish", "accrue", "accumulate", "accurate", "accuse",
  "accustomed", "acerbic", "acknowledge", "acquaintance", "acquiesce",
  "acquire", "acquit", "acrid", "acrobat", "acrylic", "act",
  "activate", "active", "activist", "acute", "adage", "adapt", "add",
  "addict", "addition", "address", "adequate", "adhere", "adjacent",
  "adjourn", "adjust", "administer", "admire", "admission", "admit",
  "adobe", "adopt", "adore", "adorn", "adult", "adultery", "advance",
  "advantage", "adventure", "adversary", "adverse", "advertise",
  "advice", "advise", "advocate", "aerial", "aerobic", "affair",
  "affect", "affection", "affirm", "affix", "afflict", "affluent",
  "afford", "affront", "afraid", "aftermath", "afternoon", "again",
  "against", "age", "agency", "agenda", "agent", "aggressive",
  "aggravate", "aghast", "agile", "agitate", "agnostic", "agree",
  "agriculture", "ahead", "aid", "aim", "air", "airplane", "airport",
  "alarmed", "album", "alcohol", "alert", "algae", "alien", "align",
  "alike", "alive", "allure", "ally", "almond", "almost", "alone",
  "along", "aloud", "alphabet", "already", "also", "altar", "alter",
  "although", "altitude", "always", "amaze", "ambassador", "amber",
  "ambiguity", "ambition", "ambulance", "amend", "amenity", "amid",
  "amiss", "ammonia", "ammunition", "among", "amount", "ample",
  "amuse", "anachronism", "analog", "analysis", "analyze", "anarchy",
  "ancestor", "anchor", "ancient", "and", "anecdotal", "angel",
  "anger", "angle", "angular", "anguish", "animal", "ankle",
  "anniversary", "announce", "annoy", "annual", "anonymous",
  "another", "answer", "antelope", "antenna", "anthem", "anxiety",
  "any", "apart", "apartment", "apathetic", "ape", "apology",
  "apparatus", "apparel", "apparent", "appeal", "appear", "appetite",
  "applause", "apple", "appliance", "appreciate", "apprehension",
  "approach", "approve", "approximate", "apron", "apt", "aquatic",
  "arc", "arcade", "arch", "archery", "architect", "archive",
  "arctic", "ardent", "argue", "arise", "arithmetic", "arm",
  "armadillo", "armature", "aroma", "around", "arouse", "arrange",
  "arrest", "arrive", "arrogant", "arrow", "art", "artery",
  "arthritis", "article", "artificer", "artificial", "artist",
  "artistic", "ascend", "ascertain", "ascribe", "ash", "ashtray",
  "aside", "ask", "asleep", "aspect", "asphalt", "assailant",
  "assault", "assemble", "assembly", "assert", "assess", "asset",
  "assign", "assist", "associate", "assume", "assurance", "asteroid",
  "asthma", "astonish", "astound", "astronaut", "astronomer",
  "astronomy", "asylum", "athlete", "athletic", "atmosphere", "atom",
  "atomic", "atrocious", "attach", "attack", "attain", "attempt",
  "attend", "attention", "attentive", "attitude", "attorney",
  "attract", "attribute", "audience", "audit", "augment", "aunt",
  "authentic", "author", "authority", "authorization", "autopilot",
  "autumn", "auxiliary", "available", "avalanche", "avenue",
  "average", "avert", "aviation", "avoid", "await", "awake", "award",
  "aware", "awkward", "axis", "axle", "baby", "baboon", "apple",
  "banana", "cat", "dog", "elephant", "fish", "giraffe", "horse",
  "igloo", "jellyfish", "kangaroo", "lion", "monkey", "narwhal",
  "octopus", "panda", "quokka", "rhinoceros", "snake", "tiger",
  "umbrella", "violin", "walrus", "xylophone", "yacht", "zebra",
  "aardvark", "antelope", "armadillo", "baboon", "badger", "bat",
  "beaver", "bison", "boar", "bobcat", "capybara", "caribou",
  "cassowary", "cheetah", "chimpanzee", "chipmunk", "cobra", "cougar",
  "coyote", "crocodile", "deer", "dingo", "dolphin", "donkey",
  "dragonfly", "duck", "eagle", "echidna", "elk", "emu", "falcon",
  "ferret", "flamingo", "fox", "frog", "gazelle", "gecko", "gerbil",
  "gibbon", "gnu", "gorilla", "groundhog", "guinea pig", "hamster",
  "hedgehog", "hippopotamus", "hyena", "iguana", "impala", "jackal",
  "jaguar", "jellyfish", "kangaroo", "koala", "komodo dragon",
  "lemur", "leopard", "liger", "llama", "lynx", "macaque", "manatee",
  "marmot", "meerkat", "mink", "mole", "mongoose", "moose",
  "mountain goat", "narwhal", "numbat", "ocelot", "okapi",
  "orangutan", "oryx", "otter", "panda", "panther", "parakeet",
  "parrot", "peacock", "peccary", "pelican", "penguin", "pheasant",
  "pig", "platypus", "polar bear", "porcupine", "possum",
  "prairie dog", "puma", "quokka", "raccoon", "rat", "reindeer",
  "rhinoceros", "salamander", "sand dollar", "sea lion", "sea otter",
  "seahorse", "serval", "sheep", "shrew", "skunk", "sloth", "snake",
  "snow leopard", "squid", "squirrel", "starfish", "stegosaurus",
  "stingray", "stork", "swan", "tapir", "tarantula", "tiger",
  "tortoise", "toucan", "tuna", "turkey", "turtle", "unicorn",
  "urchin", "wallaby", "walrus", "warthog", "weasel", "wombat",
  "wolf", "wolverine", "zebra", "aardvark", "antelope", "armadillo",
  "baboon", "badger", "beaver", "bison", "buffalo", "camel",
  "cheetah", "chimpanzee", "chinchilla", "condor", "coyote",
  "crocodile", "deer", "dolphin", "donkey", "echidna", "elk", "emu",
  "eyelash viper", "flamingo", "fox", "giraffe", "gorilla",
  "grizzly bear", "guinea pig", "hamster", "hedgehog", "hippopotamus",
  "hyena", "impala", "jackal", "jellyfish", "joey", "kangaroo",
  "koala", "lemur", "leopard", "liger", "llama", "lynx", "macaque",
  "mandrill", "marmoset", "meerkat", "mink", "mole", "mongoose",
  "moose", "mountain goat", "mule", "narwhal", "numbat", "ocelot",
  "okapi", "orangutan", "oryx", "otter", "panda", "pelican",
  "platypus", "polar bear", "porcupine", "prairie dog", "puma",
  "quokka", "raccoon", "red panda", "reindeer", "rhinoceros",
  "sea lion", "sea otter", "serval", "sheep", "shrew", "skunk",
  "sloth", "snow leopard", "spider monkey", "squirrel", "tapir",
  "tarsier", "tiger", "wallaby", "warthog", "water buffalo", "weasel",
  "wolverine", "wombat", "woodchuck", "yak", "zebra", "elephant",
  "fish", "goat", "house", "igloo", "jellyfish", "kangaroo", "lion",
  "monkey", "nest", "octopus", "pig", "quail", "rhino", "snake",
  "turtle", "umbrella", "violin", "whale", "xylophone", "zebra",
  "ambiguous", "boisterous", "circumspect", "delectable",
  "effervescent", "ferocious", "gregarious", "haphazard",
  "imperturbable", "jejune", "knavish", "loquacious", "malevolent",
  "nemesis", "obsequious", "parsimonious", "querulous", "reticent",
  "strenuous", "treacherous", "umbrageous", "vacuous", "wanton",
  "xenophobic", "youthful", "zealous", "abracadabra", "cacophony",
  "defenestrate", "eureka", "flummox", "gallivant", "haphazardly",
  "impetuously", "jeopardize", "kilobyte", "loquaciousness",
  "maladroit", "nemesis", "obsequiously", "parsimony",
  "querulousness", "reticence", "strenuously", "treacherously",
  "umbrage", "vacuously", "wantonly", "xenophobia", "youthfulness",
  "zealously"};

    ArrayList<String> dictionary2 = new ArrayList<>();
    ArrayList<String> dictionary3 = new ArrayList<>();
    ArrayList<Integer> numDuplicates = new ArrayList<>();
    ArrayList<Integer> positions = new ArrayList<>();
    boolean duplicate;
    for(int i = 0; i < dictionary.length; i++) 
    {
    duplicate = false;
    for(int j = 0; j < dictionary2.size(); j++) 
    {
      if(dictionary[i].equals(dictionary2.get(j))) 
      {
          duplicate = true;
          positions.add(i);
          break;
          }
      }
      if (!duplicate) 
      {
        dictionary2.add(dictionary[i]);
        } else {
          dictionary3.add(dictionary[i]);
        }
      }
      System.out.println("Words with duplicates are: ");
      for (int v = 0; v < dictionary3.size(); v++) 
      {
        int numOfDuplicates = 0;
            for (int i = 0; i < dictionary.length; i++) 
            {
              if(dictionary3.get(v).equals(dictionary[i])) 
              {
                  numOfDuplicates++;
                  if (numOfDuplicates > 0) 
                  {
                      positions.add(i);
                  }
              }
          }
          numDuplicates.add(numOfDuplicates);
          System.out.print(dictionary3.get(v) + " is in the array " + numDuplicates.get(v) + " times in positions: ");
          for (int x = 0; x < positions.size(); x++) 
          {
            System.out.print(positions.get(x));
              if (x < positions.size() - 1) 
              {
                System.out.print(", ");
              }
          }
          System.out.println("");
          positions.clear();
        }
        System.out.println("");
        System.out.println("The newly built list without duplicates is: ");
        for (int i = 0; i < dictionary2.size(); i++) {
            System.out.print("\"" + dictionary2.get(i) + "\"");
            if (i < dictionary2.size() - 1) 
            {
                System.out.print(", ");
            }
        }
  }
}